"use client";
import {useMemo,useState} from 'react';
import {ArrowDownToLine} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Table,TableHeader,TableBody,TableHead,TableRow,TableCell} from '@/components/ui/table';
import {Pagination,PaginationContent,PaginationItem,PaginationNext,PaginationPrevious} from '@/components/ui/pagination';
import {Picker,fixed,pct,dateLabel,download} from './ui';
import {Stat} from './scouting';
import type {Season,Report,Prediction} from './types';
export function Audit({data,report}:{data:Season;report:Report}){
const [mode,setMode]=useState('all'),[search,setSearch]=useState(''),[page,setPage]=useState(0),[grid,setGrid]=useState(false);
const rows=data.predictions;const selected=useMemo(()=>rows.filter(p=>(`${p.homeName} ${p.awayName}`.toLowerCase().includes(search.toLowerCase()))&&(mode==='all'||mode==='miss'&&((p.prob>=.5)!==Boolean(p.outcome))||mode==='upset'&&(p.outcome?p.prob:1-p.prob)<.35)),[rows,mode,search]);
const maxPage=Math.max(0,Math.ceil(selected.length/25)-1),current=Math.min(page,maxPage);const shown=selected.slice(current*25,(current+1)*25);
const role=data.season===2023?'Parameter-selection season':data.season===2024||data.season===2025?'Locked-parameter holdout':data.season===2026?'Current season, partial sample':'Development / warm-up season';
const ev=['Saturday model','Elo','Adjusted scoring','50/50 baseline'].map((model,i)=>{const ps=rows.map(r=>i===0?r.prob:i===1?r.elo:i===2?r.scoreProb:.5);return {model,n:rows.length,accuracy:ps.filter((p,j)=>(p>=.5)===Boolean(rows[j].outcome)).length/rows.length,brier:ps.reduce((a,p,j)=>a+(p-rows[j].outcome)**2,0)/rows.length,logLoss:-ps.reduce((a,p,j)=>a+rows[j].outcome*Math.log(Math.max(p,1e-9))+(1-rows[j].outcome)*Math.log(Math.max(1-p,1e-9)),0)/rows.length}});
const bins=Array.from({length:10},(_,i)=>{const b=rows.filter(r=>Math.min(9,Math.floor(r.prob*10))===i);const actual=b.reduce((s,r)=>s+r.outcome,0)/(b.length||1),pred=b.reduce((s,r)=>s+r.prob,0)/(b.length||1);const z=1.96,n=b.length,den=1+z*z/(n||1),center=(actual+z*z/(2*(n||1)))/den,half=z*Math.sqrt(actual*(1-actual)/(n||1)+z*z/(4*(n||1)**2))/den;return {n,actual,pred,lo:center-half,hi:center+half}});
return <><div className="section-heading"><div><h1>Show the work<span>.</span></h1><p>Historical predictions, including the ones that missed.</p></div><Button variant="outline" onClick={()=>download(`saturday-predictions-${data.season}.csv`,rows)}><ArrowDownToLine size={16}/>Export predictions</Button></div><div className="audit-intro"><div><span className="audit-year">2024 + 2025</span><h2>The untouched seasons</h2><p>All 53 candidates were compared using 2023 only. The chosen settings were frozen before scoring the two holdout seasons.</p></div><div className="stat-strip"><Stat label="Winner accuracy" value={pct(report.holdout.accuracy)} note={`${report.holdout.n.toLocaleString()} FBS games`}/><Stat label="Brier score" value={fixed(report.holdout.brier,3)} note="Lower is better; 0.25 = 50/50"/><Stat label="Margin MAE" value={fixed(report.holdout.mae)} note="Points, average absolute error"/></div></div>
<div className="two-col"><section className="surface"><div className="panel-title"><h2>{data.season}: the benchmark</h2><span className="data-role">{role}</span></div><p className="subcopy">Full available season. The week selector does not restrict this audit.</p><Table><TableHeader><TableRow>{['Model','Accuracy','Brier ↓','Log loss ↓'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{ev.map((m,i)=><TableRow key={m.model} className={i===0?'selected-model':''}><TableCell>{m.model}</TableCell><TableCell>{pct(m.accuracy)}</TableCell><TableCell>{fixed(m.brier,3)}</TableCell><TableCell>{fixed(m.logLoss,3)}</TableCell></TableRow>)}</TableBody></Table><p className="fine-print">{rows.length} completed FBS vs. FBS games. The 50/50 row’s accuracy uses a fixed home-team tiebreak; its Brier and log-loss values are the useful baselines.</p></section><section className="surface"><h2>Do 70% favorites win 70% of the time?</h2><p className="subcopy">{data.season} home-win probability calibration. Bars show 95% Wilson intervals.</p><svg viewBox="0 0 470 315" className="calibration-chart" role="img" aria-label="Predicted home-win probability versus observed home-win frequency"><rect x="52" y="20" width="350" height="240" fill="#f3f7f9"/>{[0,.25,.5,.75,1].map(n=><g key={n}><line x1="52" x2="402" y1={260-n*240} y2={260-n*240} stroke="#dce5eb"/><text x="44" y={264-n*240} textAnchor="end">{n*100}%</text><text x={52+n*350} y="280" textAnchor="middle">{n*100}%</text></g>)}<line x1="52" y1="260" x2="402" y2="20" stroke="#9bacb6" strokeDasharray="5 5"/>{bins.filter(b=>b.n).map((b,i)=><g key={i}><line x1={52+b.pred*350} x2={52+b.pred*350} y1={260-b.lo*240} y2={260-b.hi*240} stroke="#83a8bb" strokeWidth="2"/><circle cx={52+b.pred*350} cy={260-b.actual*240} r={Math.min(9,3+Math.sqrt(b.n)/3)} fill="#1768ac"><title>{b.n} games; mean prediction {pct(b.pred)}, observed {pct(b.actual)}</title></circle></g>)}<text x="227" y="309" textAnchor="middle">Predicted home win probability</text></svg><p className="fine-print">Vertical axis: observed home wins. Small bins have wide uncertainty; the diagonal is perfect calibration.</p></section></div>
<section className="surface"><div className="panel-title"><h2>How the formula earned its place</h2><Button variant="outline" onClick={()=>setGrid(!grid)}>{grid?'Hide candidates':'See all 53 candidates'}</Button></div><p className="subcopy">Validation picked adjusted scoring alone: Elo blend weight {report.config.eloWeight}. No holdout result was used to choose this setting.</p><div className="selection-summary"><div><strong>12</strong><span>Elo settings</span></div><div><strong>36</strong><span>Scoring settings</span></div><div><strong>5</strong><span>Blend weights</span></div><div><strong>2023</strong><span>Selection data only</span></div></div>{grid&&<Table><TableHeader><TableRow><TableHead>Family</TableHead><TableHead>Parameters</TableHead><TableHead>2023 log loss</TableHead><TableHead>2023 Brier</TableHead></TableRow></TableHeader><TableBody>{report.candidates.map((c,i)=><TableRow key={i}><TableCell>{c.family}</TableCell><TableCell><code>{Object.entries(c.params).map(([k,v])=>`${k}=${v}`).join(', ')}</code></TableCell><TableCell>{fixed(c.logLoss,4)}</TableCell><TableCell>{fixed(c.brier,4)}</TableCell></TableRow>)}</TableBody></Table>}</section>
<section className="surface ledger"><div className="panel-title"><div><h2>The prediction ledger</h2><p className="subcopy">Before-week probabilities against final results. Every game is inspectable.</p></div><Button variant="outline" onClick={()=>download(`saturday-filtered-${data.season}.csv`,selected)}>Export filtered</Button></div><div className="ledger-filters"><Input aria-label="Search prediction teams" placeholder="Search either team…" value={search} onChange={e=>{setSearch(e.target.value);setPage(0)}}/><Picker label="Show" value={mode} onChange={v=>{setMode(v);setPage(0)}} options={[{value:'all',label:'All predictions'},{value:'miss',label:'Incorrect picks'},{value:'upset',label:'Upsets under 35%'}]}/><span>{selected.length} games</span></div><Table><TableHeader><TableRow>{['Date','Matchup','Final','Home win chance','Predicted margin','Outcome'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{shown.map(p=><PredictionRow key={p.id} p={p}/>)}</TableBody></Table>{!shown.length&&<p className="empty">No games match these filters. Try another team or show all predictions.</p>}<Pagination><PaginationContent><PaginationItem><PaginationPrevious href="#" aria-disabled={current===0} onClick={e=>{e.preventDefault();setPage(Math.max(0,current-1))}}/></PaginationItem><PaginationItem><span className="page-count">{current+1} / {maxPage+1}</span></PaginationItem><PaginationItem><PaginationNext href="#" aria-disabled={current===maxPage} onClick={e=>{e.preventDefault();setPage(Math.min(maxPage,current+1))}}/></PaginationItem></PaginationContent></Pagination></section>
</>}
function PredictionRow({p}:{p:Prediction}){const correct=(p.prob>=.5)===Boolean(p.outcome);return <TableRow><TableCell>{dateLabel(p.date)}</TableCell><TableCell><strong>{p.awayName}</strong><small className="muted">{p.neutral?'vs.':'at'} {p.homeName}</small></TableCell><TableCell>{p.as}–{p.hs}</TableCell><TableCell>{pct(p.prob)}</TableCell><TableCell>{p.margin>=0?'+':''}{p.margin.toFixed(1)}<small className="muted">Home team</small></TableCell><TableCell><span className={correct?'result-win':'result-loss'}>{correct?'Correct':'Miss'}</span></TableCell></TableRow>}
