"use client";
import {useEffect,useMemo,useState} from 'react';
import {asset} from '@/lib/paths';
import {Button} from '@/components/ui/button';
import {Table,TableHeader,TableBody,TableHead,TableRow,TableCell} from '@/components/ui/table';
import {Picker,dateLabel,download} from './ui';
import type {Season,Snapshot} from './types';
type Values=Record<string,number|null>;
type Definition={key:string;label:string;group:string;kind:string;format:string;higher:boolean|null;description:string|null};
type BoxRow={gameId:string;teamId:string;opponentId:string;date:string;week:number;home:boolean;neutral:boolean;fbs:boolean;own:Values;opponent:Values|null};
type BoxData={season:number;definitions:Definition[];ratios:Record<string,string[]>;source:string;rows:BoxRow[]};
function format(v:number|null|undefined,d:Definition){return v==null?'—':d.format==='percent'?`${(v*100).toFixed(1)}%`:v.toFixed(d.format==='number'?1:2)}
function aggregate(rows:BoxRow[],side:'own'|'opponent',def:Definition,ratios:BoxData['ratios']){
 const pairs=ratios[def.key];const values=rows.map(r=>r[side]).filter((r):r is Values=>r!==null);
 if(pairs){const valid=values.filter(r=>r[pairs[0]]!=null&&r[pairs[1]]!=null);const denominator=valid.reduce((s,r)=>s+(r[pairs[1]]??0),0);return denominator?valid.reduce((s,r)=>s+(r[pairs[0]]??0),0)/denominator:null}
 const nums=values.map(r=>r[def.key]).filter((v):v is number=>v!=null);return nums.length?nums.reduce((a,b)=>a+b,0)/nums.length:null;
}
export function DataExplorer({data,snapshot,week,teamId}:{data:Season;snapshot:Snapshot;week:string;teamId:string}){
 const [box,setBox]=useState<BoxData|null>(null),[error,setError]=useState(false),[side,setSide]=useState<'own'|'opponent'>('own'),[split,setSplit]=useState('all'),[group,setGroup]=useState('all'),[selected,setSelected]=useState(['totalYards','yardsPerPlay','passYpa','rushYpa','thirdRate','turnovers']),[expanded,setExpanded]=useState<string|null>(null);
 useEffect(()=>{setBox(null);setError(false);const c=new AbortController();fetch(asset(`/data/box-${data.season}.json`),{signal:c.signal}).then(r=>{if(!r.ok)throw Error();return r.json()}).then(d=>setBox(d as BoxData)).catch(e=>{if(e.name!=='AbortError')setError(true)});return()=>c.abort()},[data.season]);
 const before=useMemo(()=>new Set(data.weeks.slice(0,data.weeks.indexOf(Number(week)))),[data.weeks,week]);
 const rows=useMemo(()=>box?.rows.filter(r=>r.teamId===teamId&&before.has(r.week)&&(split==='all'||split==='fbs'&&r.fbs||split==='home'&&r.home&&!r.neutral||split==='away'&&!r.home&&!r.neutral||split==='neutral'&&r.neutral))??[],[box,teamId,before,split]);
 const defs=box?.definitions.filter(d=>selected.includes(d.key))??[];
 const league=useMemo(()=>{if(!box)return {};const result:Record<string,number[]>={};const ids=new Set(snapshot.teams.map(t=>t.id));const grouped:Record<string,BoxRow[]>={};for(const r of box.rows)if(before.has(r.week)&&ids.has(r.teamId)&&(split==='all'||split==='fbs'&&r.fbs||split==='home'&&r.home&&!r.neutral||split==='away'&&!r.home&&!r.neutral||split==='neutral'&&r.neutral))(grouped[r.teamId]??=[]).push(r);for(const d of box.definitions)result[d.key]=Object.values(grouped).map(rs=>aggregate(rs,side,d,box.ratios)).filter((v):v is number=>v!==null);return result},[box,before,snapshot.teams,side,split]);
 if(!box)return <section className="surface" role="status">{error?'Detailed game data could not load. Refresh to retry.':'Loading the game-by-game data workbench…'}</section>;
 const detail=rows.find(r=>r.gameId===expanded);const names=new Map(data.games.flatMap(g=>[[g.home,g.homeName],[g.away,g.awayName]] as [string,string][]));
 return <section className="surface data-workbench"><div className="panel-title"><div><h2>The data workbench</h2><p className="subcopy">30 selectable statistics. Raw totals, calculated efficiency and every available game box score.</p></div><Button variant="outline" onClick={()=>download(`${teamId}-${data.season}-${side}-metrics.csv`,rows.map(r=>({date:r.date,opponent:names.get(r.opponentId),...Object.fromEntries(defs.map(d=>[d.key,r[side]?.[d.key]??null]))})))}>Export selected data</Button></div>
 <div className="ledger-filters"><Picker label="Ball side" value={side} onChange={v=>setSide(v as typeof side)} options={[{value:'own',label:'Team offense & possession'},{value:'opponent',label:'Opponent output / allowed'}]}/><Picker label="Games" value={split} onChange={setSplit} options={[{value:'all',label:'All opponents'},{value:'fbs',label:'FBS only'},{value:'home',label:'Home'},{value:'away',label:'Away'},{value:'neutral',label:'Neutral'}]}/><span>{rows.length} available box scores</span></div>
 <details className="metric-controls"><summary>Choose statistics ({selected.length} selected)</summary><Picker label="Metric category" value={group} onChange={setGroup} options={[{value:'all',label:'All categories'},...Array.from(new Set(box.definitions.map(d=>d.group))).map(g=>({value:g,label:g}))]}/><div className="metric-options">{box.definitions.filter(d=>group==='all'||d.group===group).map(d=><label key={d.key}><input type="checkbox" checked={selected.includes(d.key)} onChange={()=>setSelected(prev=>prev.includes(d.key)?prev.filter(k=>k!==d.key):[...prev,d.key])}/><span>{d.label}<small>{d.kind==='calculated'?'Calculated':'Source statistic'}</small></span></label>)}</div></details>
 <Table><TableHeader><TableRow><TableHead>Selected metric</TableHead><TableHead>Team aggregate</TableHead><TableHead>FBS team mean</TableHead><TableHead>Favorable percentile</TableHead></TableRow></TableHeader><TableBody>{defs.map(d=>{const value=aggregate(rows,side,d,box.ratios),peers=league[d.key]??[];const average=peers.length?peers.reduce((a,b)=>a+b,0)/peers.length:null;const higher=side==='opponent'?!d.higher:d.higher;const rank=value==null||d.higher===null||!peers.length?null:100*peers.filter(v=>higher?v<=value:v>=value).length/peers.length;return <TableRow key={d.key}><TableCell><strong>{d.label}</strong><small className="muted">{box.ratios[d.key]?'Ratio of season totals':'Per available game'}</small></TableCell><TableCell>{format(value,d)}</TableCell><TableCell>{format(average,d)}</TableCell><TableCell>{rank===null?'Descriptive only':`${rank.toFixed(0)} / 100`}<small className="muted">{peers.length} FBS teams with data</small></TableCell></TableRow>})}</TableBody></Table>
 <p className="fine-print">Rates use summed numerators and denominators. The FBS reference is the unweighted mean of team aggregates in the same split and snapshot. Percentiles describe available data, not opponent-adjusted strength. In the opponent view, fewer allowed yards is favorable; opponent turnovers represent takeaways.</p>
 <h3>Game-by-game evidence</h3><p className="subcopy">Select a game to inspect all 30 statistics for both teams.</p>
 <Table><TableHeader><TableRow><TableHead>Date</TableHead><TableHead>Opponent</TableHead>{defs.map(d=><TableHead key={d.key}>{d.label}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map(r=><TableRow key={r.gameId}><TableCell>{dateLabel(r.date)}</TableCell><TableCell><button className="text-link" onClick={()=>setExpanded(expanded===r.gameId?null:r.gameId)} aria-expanded={expanded===r.gameId}>{names.get(r.opponentId)??r.opponentId}</button><small className="muted">{r.neutral?'Neutral':r.home?'Home':'Away'}{!r.fbs?' · non-FBS':''}</small></TableCell>{defs.map(d=><TableCell key={d.key}>{format(r[side]?.[d.key],d)}</TableCell>)}</TableRow>)}</TableBody></Table>
 {!rows.length&&<p className="empty">No box scores in this split before the selected week.</p>}{!defs.length&&<p className="empty">Choose statistics above to build your comparison.</p>}
 {detail&&<div className="game-detail"><div className="panel-title"><h3>{dateLabel(detail.date)} · vs. {names.get(detail.opponentId)}</h3><Button variant="outline" onClick={()=>setExpanded(null)}>Close game details</Button></div><Table><TableHeader><TableRow><TableHead>Statistic</TableHead><TableHead>Team</TableHead><TableHead>Opponent</TableHead><TableHead>Definition</TableHead></TableRow></TableHeader><TableBody>{box.definitions.map(d=><TableRow key={d.key}><TableCell>{d.label}</TableCell><TableCell>{format(detail.own[d.key],d)}</TableCell><TableCell>{format(detail.opponent?.[d.key],d)}</TableCell><TableCell>{d.description??'Reported in the source box score.'}</TableCell></TableRow>)}</TableBody></Table><a className="text-link" href={`https://www.espn.com/college-football/boxscore/_/gameId/${detail.gameId}`} target="_blank" rel="noreferrer">Open source box score ↗</a></div>}
 <details><summary>Definitions and source</summary><p>{box.source}</p><dl className="dictionary">{box.definitions.map(d=><div key={d.key}><dt>{d.label}</dt><dd>{d.description??'Reported in the source team box score.'}</dd></div>)}</dl><p>Missing statistics are shown as —. No zero is fabricated for a missing box score or a zero-attempt rate. Team points include defensive and special-teams scores; play-volume metrics are proxies.</p></details>
 </section>;
}
