"use client";
import {useMemo,useState} from 'react';
import {ArrowLeftRight,ArrowDownToLine} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Table,TableHeader,TableBody,TableHead,TableRow,TableCell} from '@/components/ui/table';
import type {Team,Season,Snapshot,Report} from './types';
import {Picker,Logo,signed,fixed,pct,dateLabel,download} from './ui';
import {modelPredict,featureNames} from '@/lib/model';
import {predict} from '@/lib/predict';
export function Matchup({data,snapshot,report,initial,week}:{data:Season;snapshot:Snapshot;report:Report;initial:string;week:string}){
const [aid,setA]=useState(initial),[bid,setB]=useState('333'),[venue,setVenue]=useState<'a'|'b'|'neutral'>('neutral');
const a=snapshot.teams.find(t=>t.id===aid)??snapshot.teams[0],b=snapshot.teams.find(t=>t.id===bid)??snapshot.teams[1];
const result=useMemo(()=>a.id===b.id?null:predict(a,b,snapshot.mu,venue,data.scoringConfig??report.config),[a,b,snapshot.mu,venue,report.config,data.scoringConfig]);

const r=result;const official=a.modelState&&b.modelState&&data.model?modelPredict(a.modelState,b.modelState,venue==='neutral'?0:venue==='a'?1:-1,data.model):null;const probability=official?.probability??r?.probability;const opts=snapshot.teams.slice().sort((a,b)=>a.name.localeCompare(b.name)).map(t=>({value:t.id,label:t.name}));
const history=data.games.filter(g=>(g.home===a.id&&g.away===b.id||g.home===b.id&&g.away===a.id)&&snapshot.through&&g.date<=snapshot.through);
const comps:[string,keyof Team,boolean,string][]=[['Power rating','power',true,'pts'],['Adjusted offense','offense',true,'pts'],['Adjusted defense','defense',true,'pts'],['Schedule strength','sos',true,'pts'],['Points scored','pf',true,'/ game'],['Points allowed','pa',false,'/ game'],['Total yards','yards',true,'/ game'],['Yards allowed','yardsAllowed',false,'/ game'],['Third-down conversion','thirdDown',true,'%'],['Turnovers committed','turnovers',false,'/ game']];
return <><div className="section-heading"><div><h1>Compare two teams</h1><p>Choose two teams and a venue to estimate who would win using the selected ratings.</p></div><Button variant="outline" disabled={!r} onClick={()=>r&&download('saturday-matchup.csv',[{season:data.season,week,...r,probability,modelVersion:data.model?.version}])}><ArrowDownToLine size={16}/>Export matchup</Button></div><div className="matchup-controls"><Picker label="Team A" value={a.id} onChange={setA} options={opts}/><Button variant="outline" aria-label="Swap teams" onClick={()=>{setA(b.id);setB(a.id);setVenue(venue==='a'?'b':venue==='b'?'a':'neutral')}}><ArrowLeftRight size={18}/></Button><Picker label="Team B" value={b.id} onChange={setB} options={opts}/><Picker label="Venue" value={venue} onChange={v=>setVenue(v as typeof venue)} options={[{value:'neutral',label:'Neutral field'},{value:'a',label:`${a.short} at home`},{value:'b',label:`${b.short} at home`}]}/></div>
{!r?<div className="notice">Choose two different teams to run a comparison.</div>:<><section className="matchup-scoreboard"><div className="matchup-team"><Logo team={a} size={72}/><span>#{a.modelRank??a.rank} / {a.wins}–{a.losses}</span><h2>{a.short}</h2><strong>{pct(probability??0)}</strong><small>Win probability</small></div><div className="matchup-center matchup-pick"><span>Model pick</span><h2>{(probability??0)>=.5?a.short:b.short}</h2><p>{Math.abs((probability??.5)-.5)<.1?'Close matchup':'Favored to win'}</p><small>{venue==='neutral'?'Neutral field':`${venue==='a'?a.short:b.short} at home`}</small></div><div className="matchup-team"><Logo team={b} size={72}/><span>#{b.modelRank??b.rank} / {b.wins}–{b.losses}</span><h2>{b.short}</h2><strong>{pct(1-(probability??0))}</strong><small>Win probability</small></div><div className="probability-track"><span style={{width:`${(probability??0)*100}%`,background:a.color}}/><span style={{flex:1,background:b.color}}/></div></section><p className="model-status">Saturday model. Win chance uses the complete model; points use its scoring component. Computed from the downloadable snapshot. Projections use the selected snapshot, not a scheduled fixture.</p>
<details className="advanced-details"><summary>Why this prediction? Model inputs &amp; scoring estimate</summary><p className="subcopy">Scoring-component estimate: {a.short} {Math.max(0,r.aScore).toFixed(1)} – {b.short} {Math.max(0,r.bScore).toFixed(1)}. The complete model can favor a different team.</p>{official&&<section className="surface"><h2>Inside the win probability</h2><p className="subcopy">Contributions to {a.short}’s log odds. Positive favors {a.short}; these are not point margins.</p><dl className="stat-list">{official.contributions.map((value,i)=>data.model?.coefficients[i]!==0&&<div key={i}><dt>{data.model?.featureNames?.[i]??featureNames[i]}</dt><dd>{signed(value)}</dd></div>)}</dl><p className="fine-print">These log-odds contributions describe the complete current probability model. Hypothetical matchups assume equal rest. Inspect Model audit for the chosen weights and validation results.</p></section>}<div className="two-col"><section className="surface"><h2>Where the margin comes from</h2><p className="subcopy">Contributions to {a.short}’s expected margin against {b.short}.</p><div className="contributions">{[['Offense difference',r.offenseEdge],['Defense difference',r.defenseEdge],['Home-field effect',r.homeEdge],['Expected margin',r.margin]].map(([label,v])=><div key={label}><span>{label}</span><div className="contribution-bar"><i style={{width:`${Math.min(100,Math.abs(Number(v))/35*100)}%`,background:Number(v)>=0?'#1768ac':'#a45c50'}}/></div><strong>{signed(Number(v))}</strong></div>)}</div><p className="fine-print">Offense and defense are opponent-adjusted scoring components. The score model’s probability is {pct(r.scoringProbability)}; Elo independently says {pct(r.eloProbability)}.</p></section><section className="surface uncertainty"><h2>A forecast, with room for football.</h2><p>In 2024–2025, 80% of absolute margin errors were no greater than <strong>{report.residual80.toFixed(1)} points</strong>. That is a historical error summary, not a matchup-specific confidence interval.</p><div className="error-range"><span>{signed(r.margin-report.residual80)}</span><div/><strong>{signed(r.margin)}</strong><div/><span>{signed(r.margin+report.residual80)}</span></div><p className="fine-print">Illustrative range around {a.short}’s margin. Injuries, depth charts, transfers, weather and in-game decisions are not model inputs. Offense and defense include special-teams and defensive scores.</p></section></div>
</details><section className="surface compare-surface"><div className="panel-title"><h2>The head-to-head profile</h2><span className="muted">Raw statistics include all opponents</span></div><Table><TableHeader><TableRow><TableHead>Metric</TableHead><TableHead>{a.short}</TableHead><TableHead>Relative profile</TableHead><TableHead>{b.short}</TableHead></TableRow></TableHeader><TableBody>{comps.map(([label,key,higher,unit])=>{const av=a[key] as number|null,bv=b[key] as number|null;const total=Math.abs(av??0)+Math.abs(bv??0)||1;return <TableRow key={key}><TableCell>{label}<small className="muted">{unit}</small></TableCell><TableCell className={av!=null&&bv!=null&&(higher?av>bv:av<bv)?'comparison-best':''}>{unit==='%'?pct(av):fixed(av)}</TableCell><TableCell><div className="compare-track"><span style={{width:`${Math.abs(av??0)/total*100}%`,background:'#1768ac'}}/><span style={{flex:1,background:'#92acb9'}}/></div></TableCell><TableCell className={av!=null&&bv!=null&&(higher?bv>av:bv<av)?'comparison-best':''}>{unit==='%'?pct(bv):fixed(bv)}</TableCell></TableRow>})}</TableBody></Table><p className="fine-print">Blue text indicates the favorable value; schedule strength describes difficulty, not quality. Bars compare magnitudes; negative ratings remain signed in the numbers.</p></section>
<section className="surface"><h2>This season’s meetings</h2>{history.length?history.map(g=><p className="meeting" key={g.id}>{dateLabel(g.date)} · {g.awayName} {g.as} at {g.homeName} {g.hs}{g.neutral?' (neutral)':''}</p>):<p className="subcopy">These teams have no completed head-to-head game in the selected season before this snapshot.</p>}</section></>}
</>}
