"use client";
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {ArrowLeftRight,ArrowDownToLine} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Table,TableHeader,TableBody,TableHead,TableRow,TableCell} from '@/components/ui/table';
import type {Team,Season,Snapshot,Report} from './types';
import {Picker,SearchPicker,Logo,signed,fixed,pct,dateLabel,download} from './ui';
import {modelPredict,featureNames} from '@/lib/model';
import {predict} from '@/lib/predict';
import {teamPath} from '@/lib/routes';
import {fullModelScore} from '@/lib/projected-score';
export function Matchup({data,snapshot,report,initial,initialB,initialVenue='neutral',fixtureDate,week,onSelectionChange}:{data:Season;snapshot:Snapshot;report:Report;initial:string;initialB?:string;initialVenue?:'a'|'b'|'neutral';fixtureDate?:string;week:string;onSelectionChange?:(a:string,b:string,venue:'a'|'b'|'neutral')=>void}){
const fallbackB=initial==='333'?'194':'333';
const [aid,setA]=useState(initial),[bid,setB]=useState(initialB??fallbackB),[venue,setVenue]=useState<'a'|'b'|'neutral'>(initialVenue);
const [gameDate,setGameDate]=useState<string|undefined>(fixtureDate);
const a=snapshot.teams.find(t=>t.id===aid)??snapshot.teams[0],b=snapshot.teams.find(t=>t.id===bid);
useEffect(()=>{onSelectionChange?.(aid,bid,venue)},[aid,bid,venue,onSelectionChange]);
const result=useMemo(()=>!b||a.id===b.id?null:predict(a,b,snapshot.mu,venue,data.scoringConfig??report.config),[a,b,snapshot.mu,venue,report.config,data.scoringConfig]);

const r=result;const official=b&&a.modelState&&b.modelState&&data.model?modelPredict(a.modelState,b.modelState,venue==='neutral'?0:venue==='a'?1:-1,data.model,gameDate):null;const probability=official?.probability??r?.probability,projected=r&&probability!=null?fullModelScore(probability,r.aScore,r.bScore):null;const opts=snapshot.teams.slice().sort((a,b)=>a.name.localeCompare(b.name)).map(t=>({value:t.id,label:t.name}));
const history=b?data.games.filter(g=>(g.home===a.id&&g.away===b.id||g.home===b.id&&g.away===a.id)&&snapshot.through&&g.date<=snapshot.through):[];
const comps:{label:string;value:(team:Team)=>number|null|undefined;higher:boolean;format:'number'|'percent'|'rank';unit:string}[]=[
  {label:'National power rank',value:t=>t.modelRank??t.rank,higher:false,format:'rank',unit:'FBS'},
  {label:'Strength index',value:t=>t.winIndex,higher:true,format:'percent',unit:'neutral field'},
  {label:'Scoring power',value:t=>t.power,higher:true,format:'number',unit:'pts'},
  {label:'Adjusted offense',value:t=>t.offense,higher:true,format:'number',unit:'pts'},
  {label:'Adjusted defense',value:t=>t.defense,higher:true,format:'number',unit:'pts prevented'},
  {label:'Schedule strength',value:t=>t.sos,higher:true,format:'number',unit:'pts'},
  {label:'Net EPA per play',value:t=>t.modelState?.q?.[1],higher:true,format:'number',unit:'adjusted'},
  {label:'First-down creation',value:t=>t.modelState?.q?.[8],higher:true,format:'number',unit:'adjusted'},
  {label:'Passing EPA',value:t=>t.modelState?.q?.[9],higher:true,format:'number',unit:'adjusted'},
  {label:'Rushing EPA',value:t=>t.modelState?.q?.[10],higher:true,format:'number',unit:'adjusted'},
  {label:'Yards per play',value:t=>t.modelState?.q?.[11],higher:true,format:'number',unit:'adjusted'},
  {label:'Explosive-play rate',value:t=>t.modelState?.q?.[12],higher:true,format:'number',unit:'adjusted'},
  {label:'Points scored',value:t=>t.pf,higher:true,format:'number',unit:'/ game'},
  {label:'Points allowed',value:t=>t.pa,higher:false,format:'number',unit:'/ game'},
  {label:'Total yards',value:t=>t.yards,higher:true,format:'number',unit:'/ game'},
  {label:'Yards allowed',value:t=>t.yardsAllowed,higher:false,format:'number',unit:'/ game'},
  {label:'Third-down conversion',value:t=>t.thirdDown,higher:true,format:'percent',unit:'rate'},
  {label:'Turnovers committed',value:t=>t.turnovers,higher:false,format:'number',unit:'/ game'}
];
const displayMetric=(value:number|null|undefined,format:'number'|'percent'|'rank')=>format==='rank'?(value==null?'—':`#${value}`):format==='percent'?pct(value):fixed(value,3);
return <><div className="section-heading"><div><h1>Compare two teams</h1><p>Choose two teams and a venue to estimate who would win using the selected ratings.</p></div><Button variant="outline" disabled={!r} onClick={()=>r&&download('saturday-matchup.csv',[{season:data.season,week,...r,projectedAScore:projected?.aScore,projectedBScore:projected?.bScore,projectedMargin:projected?.margin,probability,modelVersion:data.model?.version}])}><ArrowDownToLine size={16}/>Export matchup</Button></div><div className="matchup-controls"><SearchPicker label="Team A" value={a.id} onChange={v=>{setA(v);setGameDate(undefined)}} options={opts}/><Button variant="outline" aria-label="Swap teams" disabled={!b} onClick={()=>{if(!b)return;setA(b.id);setB(a.id);setVenue(venue==='a'?'b':venue==='b'?'a':'neutral')}}><ArrowLeftRight size={18}/></Button><SearchPicker label="Team B" value={bid} onChange={v=>{setB(v);setGameDate(undefined)}} options={opts} placeholder="Search for an opponent…"/><Picker label="Venue" value={venue} onChange={v=>{setVenue(v as typeof venue);setGameDate(undefined)}} options={[{value:'neutral',label:'Neutral field'},{value:'a',label:`${a.short} at home`},{value:'b',label:`${b?.short??'Team B'} at home`}]}/></div>
{!b?<section className="surface matchup-empty"><span>TEAM A SELECTED</span><h2>{a.name}</h2><p>Choose an opponent above to run the v6 comparison.</p></section>:!r||!projected?<div className="notice">Choose two different teams to run a comparison.</div>:<><section className="matchup-scoreboard"><Link href={teamPath(a)} className="matchup-team"><Logo team={a} size={72}/><span>#{a.modelRank??a.rank} / {a.wins}–{a.losses}</span><h2>{a.short}</h2><strong>{pct(probability??0)}</strong><small>Win probability · team page →</small></Link><div className="matchup-center matchup-pick"><span>Expected score</span><h2>{projected.aScore.toFixed(1)}–{projected.bScore.toFixed(1)}</h2><p>{Math.abs((probability??.5)-.5)<.1?'Close matchup':'Model pick: '+((probability??0)>=.5?a.short:b.short)}</p><small>{venue==='neutral'?'Neutral field':`${venue==='a'?a.short:b.short} at home`}</small></div><Link href={teamPath(b)} className="matchup-team"><Logo team={b} size={72}/><span>#{b.modelRank??b.rank} / {b.wins}–{b.losses}</span><h2>{b.short}</h2><strong>{pct(1-(probability??0))}</strong><small>Win probability · team page →</small></Link><div className="probability-track"><span style={{width:`${(probability??0)*100}%`,background:a.color}}/><span style={{flex:1,background:b.color}}/></div></section><p className="model-status">The v6 win signal sets the expected margin; a historical scoring-total calibration sets the pace. {gameDate?`Scheduled ${dateLabel(gameDate)}; the published kickoff date supplies rest intervals.`:'Manual comparisons assume equal rest.'}</p>
<details className="advanced-details"><summary>Model inputs &amp; expected score</summary><p className="subcopy">Full-model expected score: {a.short} {projected.aScore.toFixed(1)} – {b.short} {projected.bScore.toFixed(1)}. Expected points describe an average outcome, not an exact final score.</p>{official&&<section className="surface"><h2>Inside the win probability</h2><p className="subcopy">Contributions to {a.short}’s log odds. Positive favors {a.short}; these are not point margins.</p><dl className="stat-list">{official.contributions.map((value,i)=>data.model?.coefficients[i]!==0&&<div key={i}><dt>{data.model?.featureNames?.[i]??featureNames[i]}</dt><dd>{signed(value,3)}</dd></div>)}</dl><p className="fine-print">These log-odds contributions describe the complete current probability model. Hypothetical matchups assume equal rest. Inspect Model performance for the chosen weights and validation results.</p></section>}<div className="two-col"><section className="surface"><h2>Scoring baseline</h2><p className="subcopy">Opponent-adjusted offense, defense and venue establish the game-total baseline.</p><div className="contributions">{[['Offense difference',r.offenseEdge],['Defense difference',r.defenseEdge],['Home-field effect',r.homeEdge],['Baseline margin',r.margin]].map(([label,v])=><div key={label}><span>{label}</span><div className="contribution-bar"><i style={{width:`${Math.min(100,Math.abs(Number(v))/35*100)}%`,background:Number(v)>=0?'#1768ac':'#a45c50'}}/></div><strong>{signed(Number(v))}</strong></div>)}</div><p className="fine-print">The complete v6 probability signal supplies the published expected margin. The scoring baseline supplies total-points context after historical calibration.</p></section><section className="surface uncertainty"><h2>Historical margin error</h2><p>In 2024–2025, 80% of absolute margin errors were no greater than <strong>{report.residual80.toFixed(1)} points</strong>. That is a historical error summary, not a matchup-specific confidence interval.</p><div className="error-range"><span>{signed(projected.margin-report.residual80)}</span><div/><strong>{signed(projected.margin)}</strong><div/><span>{signed(projected.margin+report.residual80)}</span></div><p className="fine-print">Illustrative range around {a.short}’s expected margin. Verified injuries, depth charts, complete transfer-adjusted rosters, weather and in-game decisions are unavailable.</p></section></div>
</details><section className="surface compare-surface"><div className="panel-title"><div><h2>Head-to-head profile</h2><p className="subcopy">Team quality, opponent-adjusted efficiency and season production at the selected snapshot.</p></div><span className="muted">{a.wins}–{a.losses} · {b.wins}–{b.losses}</span></div><Table><TableHeader><TableRow><TableHead>Metric</TableHead><TableHead>{a.short}</TableHead><TableHead>Relative profile</TableHead><TableHead>{b.short}</TableHead></TableRow></TableHeader><TableBody>{comps.map(metric=>{const av=metric.value(a),bv=metric.value(b),total=Math.abs(av??0)+Math.abs(bv??0)||1;return <TableRow key={metric.label}><TableCell>{metric.label}<small className="muted">{metric.unit}</small></TableCell><TableCell className={av!=null&&bv!=null&&(metric.higher?av>bv:av<bv)?'comparison-best':''}>{displayMetric(av,metric.format)}</TableCell><TableCell><div className="compare-track"><span style={{width:`${Math.abs(av??0)/total*100}%`,background:a.color}}/><span style={{flex:1,background:b.color}}/></div></TableCell><TableCell className={av!=null&&bv!=null&&(metric.higher?bv>av:bv<av)?'comparison-best':''}>{displayMetric(bv,metric.format)}</TableCell></TableRow>})}</TableBody></Table><p className="fine-print">Highlighted text indicates the favorable value. Adjusted metrics account for opponents; raw season averages include all opponents. Candidate model evidence is shown even when its fitted v6 coefficient is zero.</p></section>
<section className="surface"><h2>This season’s meetings</h2>{history.length?history.map(g=><p className="meeting" key={g.id}>{dateLabel(g.date)} · {g.awayName} {g.as} at {g.homeName} {g.hs}{g.neutral?' (neutral)':''}</p>):<p className="subcopy">These teams have no completed head-to-head game in the selected season before this snapshot.</p>}</section></>}
</>}
