"use client";
import {useEffect,useState} from 'react';
import {asset} from '@/lib/paths';
import {pct,download,Picker,dateLabel} from './ui';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Table,TableHeader,TableBody,TableHead,TableRow,TableCell} from '@/components/ui/table';
import type {Season} from './types';

type Scores={n:number;accuracy:number;brier:number;logLoss:number};
type Rating={method:string;carry:number;lam:number;memory:number;decay:number};
type Candidate=Scores&{ratingConfig:Rating;bundle:string;ridge:number};
type FpiRow={id:string;name:string;rank:number;fpi:number;previousRank:number;modelRank:number;gap:number};
type ModelReport={candidateCount:number;scope:string;protocolSha256:string;annual:Record<string,{selected:Candidate;validationYears:number[];trainingThrough:number}>;searches:{targetSeason:number;candidates:Candidate[]}[];evaluation:(Scores&{season:number;model:string})[];groups:{season:number;group:string;new:Scores;previous:Scores}[];bootstrap:{years:number[];difference:number;lower:number;upper:number;weeks:number}[];coverage:{year:number;games:number;epaPairedGames:number;talentTeams:number;teams:number}[];fpiComparison:{note:string;excludedFlaggedRows:number;matchedGames:{season:number;n:number;fpiPickAccuracy:number|null;newAccuracy:number|null;v3Accuracy:number|null}[];rankMetrics:Record<string,{meanAbsoluteRankGap:number;spearman:number}>;teams:FpiRow[]}};
const percent=(n:number)=>`${(n*100).toFixed(2)}%`;
export function ModelAudit({data}:{data:Season}){
 const [report,setReport]=useState<ModelReport|null>(null),[error,setError]=useState(false),[search,setSearch]=useState(''),[filter,setFilter]=useState('all'),[page,setPage]=useState(0),[fpiSearch,setFpiSearch]=useState('');
 useEffect(()=>{let active=true;fetch(asset('/data/model.json')).then(r=>{if(!r.ok)throw Error();return r.json()}).then(d=>{if(active)setReport(d as ModelReport)}).catch(()=>{if(active)setError(true)});return()=>{active=false}},[]);
 if(!report)return <section className="surface"><h2>The model audit</h2><p>{error?'Research data could not load. Refresh to retry.':'Loading the validation evidence...'}</p></section>;
 const annual=report.annual[String(data.season)],evaluation=report.evaluation.filter(r=>r.season===data.season),candidates=report.searches.find(r=>r.targetSeason===data.season)?.candidates??[];
 const rows=data.predictions.filter(p=>`${p.homeName} ${p.awayName}`.toLowerCase().includes(search.toLowerCase())&&(filter==='all'||filter==='miss'&&(p.prob>=.5)!==Boolean(p.outcome)||filter==='upset'&&(p.outcome?p.prob:1-p.prob)<.35));
 const maxPage=Math.max(0,Math.ceil(rows.length/30)-1),current=Math.min(page,maxPage);
 const bins=Array.from({length:10},(_,i)=>{const rr=data.predictions.filter(p=>Math.min(9,Math.floor(p.prob*10))===i);return {i,n:rr.length,p:rr.length?rr.reduce((s,r)=>s+r.prob,0)/rr.length:0,y:rr.length?rr.reduce((s,r)=>s+r.outcome,0)/rr.length:0}});
 const fpi=report.fpiComparison,fp= fpi.matchedGames.find(r=>r.season===data.season),gapRows=[...fpi.teams].filter(t=>t.name.toLowerCase().includes(fpiSearch.toLowerCase())).sort((a,b)=>Math.abs(b.gap)-Math.abs(a.gap));
 return <>
 <div className="section-heading"><div><h1>A redesigned model. An open record.</h1><p>Scoring, unit efficiency and recruiting evidence. One published forecast.</p></div><Button variant="outline" onClick={()=>download(`model-predictions-${data.season}.csv`,data.predictions)}>Export season predictions</Button></div>
 <section className="surface"><h2>Test the architecture, not one school's rank</h2><p>We compared {report.candidateCount} configurations: 24 rating designs, six input bundles and two regression penalties. Rating designs test raw scores, a 28-point margin cap, smooth blowout compression, 40% or 65% carryover, one or three prior seasons, and two prior strengths. Bundles test scoring alone, opponent-adjusted EPA, passing/rushing units, special teams, yards per play, recruiting talent, rest and nonlinear effects.</p>
 <p className="callout">Selection uses earlier-season log loss, not agreement with ESPN or a desired rank for any school. The new model improves aggregate probability scores versus v3, but does not win every subgroup. In particular, 2025 results from week 5 onward remain weaker on probability loss. Already-inspected historical seasons are retrospective evidence, not pristine prospective tests.</p>
 {annual?<><div className="timeline"><div><strong>{annual.validationYears.join(' / ')}</strong><span>Inner validation seasons</span></div><div><strong>Through {annual.trainingThrough}</strong><span>Final coefficient training</span></div><div><strong>{data.season}</strong><span>Outer evaluation season</span></div></div><p>Selected: <strong>{annual.selected.bundle.replaceAll('_',' ')}</strong>; {annual.selected.ratingConfig.method} scoring, {pct(annual.selected.ratingConfig.carry)} carryover, {annual.selected.ratingConfig.memory} prior season(s), rating penalty {annual.selected.ratingConfig.lam}, regression penalty {annual.selected.ridge}. Each inner year is itself predicted using coefficients trained only on earlier years.</p></>:<p>2018-2022 retain exploratory archive forecasts. Redesigned annual selection begins in 2023.</p>}
 <h3>Same games, three generations</h3><p className="subcopy">Full selected season, regardless of the week selector. Lower Brier and log loss are better. 2026 is partial, through September 20.</p><Table><TableHeader><TableRow>{['Model','Games','Accuracy','Brier','Log loss'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{evaluation.map(r=><TableRow key={r.model}><TableCell>{r.model}</TableCell><TableCell>{r.n}</TableCell><TableCell>{percent(r.accuracy)}</TableCell><TableCell>{r.brier.toFixed(4)}</TableCell><TableCell>{r.logLoss.toFixed(4)}</TableCell></TableRow>)}</TableBody></Table>
 <h3>Where improvement holds, and where it does not</h3><Table><TableHeader><TableRow>{['Slice','Games','New accuracy','V3 accuracy','New loss','V3 loss'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{report.groups.filter(g=>g.season===data.season&&g.new.n>0).map(g=><TableRow key={g.group}><TableCell>{g.group}</TableCell><TableCell>{g.new.n}</TableCell><TableCell>{percent(g.new.accuracy)}</TableCell><TableCell>{percent(g.previous.accuracy)}</TableCell><TableCell>{g.new.logLoss.toFixed(4)}</TableCell><TableCell>{g.previous.logLoss.toFixed(4)}</TableCell></TableRow>)}</TableBody></Table>
 {report.bootstrap.map(b=><p className="fine-print" key={b.years.join()}>{b.years.join('-')} paired week bootstrap: new minus v3 log loss {b.difference.toFixed(4)}, descriptive 95% interval [{b.lower.toFixed(4)}, {b.upper.toFixed(4)}], {b.weeks} weeks, 3,000 resamples. An interval crossing zero does not establish a reliable advantage; three weeks cannot establish long-run performance.</p>)}
 <details><summary>Inspect all {candidates.length} earlier-year validation results</summary><Table><TableHeader><TableRow>{['Inputs','Scoring design','Carry','Prior years','Rating penalty','Regression penalty','Validation loss'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{candidates.map((c,i)=><TableRow key={i}><TableCell>{c.bundle.replaceAll('_',' ')}{i===0?' / selected':''}</TableCell><TableCell>{c.ratingConfig.method}</TableCell><TableCell>{pct(c.ratingConfig.carry)}</TableCell><TableCell>{c.ratingConfig.memory}</TableCell><TableCell>{c.ratingConfig.lam}</TableCell><TableCell>{c.ridge}</TableCell><TableCell>{c.logLoss.toFixed(5)}</TableCell></TableRow>)}</TableBody></Table></details>
 </section>
 <section className="surface"><h2>ESPN as an external benchmark</h2><p>We use ESPN's published approach as methodological guidance and its dated FPI snapshots as a comparison. ESPN's full proprietary formula is unavailable. Our EPA comes from the public cfbfastR pipeline and is not ESPN's proprietary EPA.</p>
 <h3>Historical FPI-based picks, matched to the same games</h3><p className="subcopy">Only snapshots timestamped before the frozen prediction week qualify. The benchmark picks the team favored by FPI difference plus a fixed three-point home adjustment. These are our FPI-based picks, not ESPN's official game probabilities.</p>
 {fp&&fp.n>0?<Table><TableHeader><TableRow>{['Matched games','FPI-based accuracy','New model','Previous v3'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody><TableRow><TableCell>{fp.n}</TableCell><TableCell>{percent(fp.fpiPickAccuracy!)}</TableCell><TableCell>{percent(fp.newAccuracy!)}</TableCell><TableCell>{percent(fp.v3Accuracy!)}</TableCell></TableRow></TableBody></Table>:<p>No matched FPI comparison for this season.</p>}
 <p className="fine-print">Rejected {fpi.excludedFlaggedRows.toLocaleString()} flagged or undated archive rows before matching. A week label alone is not sufficient: some early-week rows contain end-of-season updates. <a href={asset('/data/fpi-paired-audit.json')} download>Download timestamp audit</a>.</p>
 <h3>Whole-field ranking agreement</h3><p>Fixed comparison: model results through September 20, 2026 versus FPI updated September 22. Independent of the selector above; not an exact same-time comparison.</p><Table><TableHeader><TableRow>{['Ranking','Mean absolute rank gap','Spearman correlation'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{[['previous','Previous v3'],['new','Redesigned model']].map(([key,label])=><TableRow key={key}><TableCell>{label}</TableCell><TableCell>{fpi.rankMetrics[key].meanAbsoluteRankGap.toFixed(2)}</TableCell><TableCell>{fpi.rankMetrics[key].spearman.toFixed(3)}</TableCell></TableRow>)}</TableBody></Table><p><a href="https://www.espn.co.uk/college-football/fpi/_/season/2026" target="_blank" rel="noreferrer">ESPN FPI source</a></p>
 <details><summary>Inspect all {fpi.teams.length} teams, largest disagreements first</summary><Input aria-label="Search FPI comparison" placeholder="Find a team in the FPI comparison..." value={fpiSearch} onChange={e=>setFpiSearch(e.target.value)}/><Table><TableHeader><TableRow>{['Team','FPI rank','Previous v3','New rank','New minus FPI'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{gapRows.map(t=><TableRow key={t.id}><TableCell>{t.name}</TableCell><TableCell>{t.rank}</TableCell><TableCell>{t.previousRank}</TableCell><TableCell>{t.modelRank}</TableCell><TableCell>{t.gap}</TableCell></TableRow>)}</TableBody></Table></details></section>
 <section className="surface"><h2>Coverage is part of the model</h2><p>Missing EPA pairs are omitted from unit fits. Missing recruiting talent is imputed to the season's FBS mean with an explicit coverage flag. Returning-production archives were investigated but excluded: their use of same-season participation cannot establish preseason availability. No invented transfer, injury or quarterback adjustments are used.</p><p className="fine-print">{report.scope}</p><details><summary>View source coverage and research files</summary><Table><TableHeader><TableRow>{['Season','FBS games','Paired EPA games','Talent teams / FBS teams'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{report.coverage.map(c=><TableRow key={c.year}><TableCell>{c.year}</TableCell><TableCell>{c.games}</TableCell><TableCell>{c.epaPairedGames}</TableCell><TableCell>{c.talentTeams} / {c.teams}</TableCell></TableRow>)}</TableBody></Table><p><a href={asset('/data/model.json')} download>Complete report and source hashes</a> / <a href={asset('/data/model-v3.json')} download>Archived v3 model</a> / <a href={asset('/data/carry-audit.json')} download>Earlier carryover-only experiment</a></p><p className="fine-print">Protocol SHA-256: {report.protocolSha256}</p></details></section>
 <section className="surface"><h2>Probability calibration</h2><p className="subcopy">Predicted home-win probabilities versus observed outcomes; small bins are uncertain.</p><Table><TableHeader><TableRow>{['Probability bin','Games','Mean forecast','Observed wins'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{bins.map(b=><TableRow key={b.i}><TableCell>{b.i*10}-{(b.i+1)*10}%</TableCell><TableCell>{b.n}</TableCell><TableCell>{b.n?pct(b.p):'Unavailable'}</TableCell><TableCell>{b.n?pct(b.y):'Unavailable'}</TableCell></TableRow>)}</TableBody></Table></section>
 <section className="surface ledger"><div className="panel-title"><h2>The prediction ledger</h2><Button variant="outline" onClick={()=>download(`filtered-predictions-${data.season}.csv`,rows)}>Export filtered</Button></div><div className="ledger-filters"><Input aria-label="Search prediction teams" placeholder="Search either team..." value={search} onChange={e=>{setSearch(e.target.value);setPage(0)}}/><Picker label="Show predictions" value={filter} onChange={v=>{setFilter(v);setPage(0)}} options={[{value:'all',label:'All predictions'},{value:'miss',label:'Incorrect picks'},{value:'upset',label:'Upsets under 35%'}]}/><span>{rows.length} games</span></div><Table><TableHeader><TableRow>{['Date','Matchup','Final score','Home win chance','Outcome'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.slice(current*30,(current+1)*30).map(p=><TableRow key={p.id}><TableCell>{dateLabel(p.date)}</TableCell><TableCell>{p.awayName}<small className="muted">{p.neutral?'vs.':'at'} {p.homeName}</small></TableCell><TableCell>{p.as}-{p.hs}</TableCell><TableCell>{pct(p.prob)}</TableCell><TableCell>{(p.prob>=.5)===Boolean(p.outcome)?'Correct':'Miss'}</TableCell></TableRow>)}</TableBody></Table>{!rows.length&&<p className="empty">No predictions match these filters.</p>}<div className="ledger-filters"><Button variant="outline" disabled={current===0} onClick={()=>setPage(current-1)}>Previous</Button><span>{current+1} / {maxPage+1}</span><Button variant="outline" disabled={current===maxPage} onClick={()=>setPage(current+1)}>Next</Button></div></section>
 </>;
}
