"use client";
import {useEffect,useState} from 'react';
import {asset} from '@/lib/paths';
import {pct,download,Picker,dateLabel} from './ui';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Table,TableHeader,TableBody,TableHead,TableRow,TableCell} from '@/components/ui/table';
import type {Season} from './types';
type Scores={n:number;accuracy:number;brier:number;logLoss:number};
type Candidate=Scores&{name:string;ridge:number;weight:number;indices:number[];folds:(Scores&{year:number})[]};
type ModelReport={annual:Record<string,{selected:Candidate;validationYears:number[];trainingThrough:number;weight:number}>;searches:{targetSeason:number;candidates:Candidate[]}[];evaluation:(Scores&{season:number;model:string})[];protocolSha256:string;scope:string;bootstrap:{season:number;weeks:number;lossDifference:number;lower:number;upper:number;resamples:number}[]};
export function ModelAudit({data}:{data:Season}){
 const [report,setReport]=useState<ModelReport|null>(null),[error,setError]=useState(false),[search,setSearch]=useState(''),[filter,setFilter]=useState('all'),[page,setPage]=useState(0);
 useEffect(()=>{fetch(asset('/data/model.json')).then(r=>{if(!r.ok)throw Error();return r.json()}).then(d=>setReport(d as ModelReport)).catch(()=>setError(true))},[]);
 if(!report)return <section className="surface"><h2>The model audit</h2><p>{error?'Research data could not load. Refresh to retry.':'Loading the validation evidence…'}</p></section>;
 const annual=report.annual[String(data.season)];const evaluation=report.evaluation.filter(r=>r.season===data.season);const candidates=report.searches.find(r=>r.targetSeason===data.season)?.candidates??[];
 const rows=data.predictions.filter(p=>`${p.homeName} ${p.awayName}`.toLowerCase().includes(search.toLowerCase())&&(filter==='all'||filter==='miss'&&(p.prob>=.5)!==Boolean(p.outcome)||filter==='upset'&&(p.outcome?p.prob:1-p.prob)<.35));
 const maxPage=Math.max(0,Math.ceil(rows.length/30)-1),current=Math.min(page,maxPage);const b=report.bootstrap.find(b=>b.season===data.season);
 const bins=Array.from({length:10},(_,i)=>{const rr=data.predictions.filter(p=>Math.min(9,Math.floor(p.prob*10))===i);return {i,n:rr.length,p:rr.length?rr.reduce((s,r)=>s+r.prob,0)/rr.length:0,y:rr.length?rr.reduce((s,r)=>s+r.outcome,0)/rr.length:0}});
 return <><div className="section-heading"><div><h1>The evidence behind the model.</h1><p>One published model. Every candidate, prediction and limitation open to inspection.</p></div><Button variant="outline" onClick={()=>download(`model-predictions-${data.season}.csv`,data.predictions)}>Export season predictions</Button></div>
 <section className="surface upgrade-audit"><h2>A calendar, not a random split</h2><p>For each target season, compare 73 prespecified configurations on the preceding three seasons. Every inner validation year is predicted using coefficients fitted only through its prior year. Select by pooled log loss, then refit through the year before the target season. In-season team ratings update only after a whole week has finished.</p>
 {annual?<div className="timeline"><div><strong>{annual.validationYears.join(' / ')}</strong><span>Inner validation seasons</span></div><div><strong>Through {annual.trainingThrough}</strong><span>Final coefficient training</span></div><div><strong>{data.season}</strong><span>Outer evaluation season</span></div></div>:<p className="callout">2018–2022 are development and warm-up archives. Their probability and scoring displays use the original exploratory scoring specification. The unified annual selection begins in 2023.</p>}
 <p className="callout">These are retrospective forward backtests using corrected historical records. The development process has already viewed later-season results; they are not described as pristine prospective tests. The richer model is not consistently better than the original scoring benchmark.</p>
 {annual&&<p>The {data.season} configuration uses <strong>{annual.selected.name.replaceAll('_',' ')}</strong>, ridge λ={annual.selected.ridge}, and {Math.round(annual.weight*100)}% efficiency probability blended with {Math.round((1-annual.weight)*100)}% opponent-adjusted scoring probability. These are internal components of the one published model, not choices the visitor must make.</p>}
 <h3>Out-of-year results</h3><p className="subcopy">Full selected season, independent of the week selector. Lower Brier and log loss are better. The 50/50 benchmark breaks tied probabilities toward the home team when reporting accuracy. {data.season===2026?'2026 is still a small, partial-season sample.':''}</p>
 <Table><TableHeader><TableRow>{['Model / benchmark','Games','Accuracy','Brier ↓','Log loss ↓'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{evaluation.map(r=><TableRow key={r.model}><TableCell>{r.model}</TableCell><TableCell>{r.n}</TableCell><TableCell>{pct(r.accuracy)}</TableCell><TableCell>{r.brier.toFixed(4)}</TableCell><TableCell>{r.logLoss.toFixed(4)}</TableCell></TableRow>)}</TableBody></Table>
 {b&&<p className="fine-print">Paired week-cluster bootstrap, {b.resamples.toLocaleString()} resamples across {b.weeks} weeks: model − original benchmark log-loss difference {b.lossDifference.toFixed(4)}, descriptive 95% interval [{b.lower.toFixed(4)}, {b.upper.toFixed(4)}]. Negative favors the model. Short seasons and dependent games limit this interval; it is not proof of superiority.</p>}
 <details><summary>Inspect all {candidates.length} configurations and validation folds</summary><Table><TableHeader><TableRow><TableHead>Inputs</TableHead><TableHead>Ridge λ</TableHead><TableHead>Efficiency weight</TableHead>{annual?.validationYears.map(y=><TableHead key={y}>{y} loss</TableHead>)}<TableHead>Pooled loss</TableHead></TableRow></TableHeader><TableBody>{candidates.map((c,i)=><TableRow key={i}><TableCell>{c.name.replaceAll('_',' ')}{i===0?' · selected':''}</TableCell><TableCell>{c.ridge}</TableCell><TableCell>{pct(c.weight)}</TableCell>{c.folds.map(f=><TableCell key={f.year}>{f.logLoss.toFixed(4)}</TableCell>)}<TableCell>{c.logLoss.toFixed(4)}</TableCell></TableRow>)}</TableBody></Table></details>
 <details><summary>Equations, features and source limitations</summary><p>Each box metric is modeled as league mean + team offense − opponent defense, with ridge shrinkage, 65% offseason carryover and 0.94 weekly decay. Inputs cover passing and rushing efficiency, third and fourth downs, turnover rate, play volume, completion, first downs, penalty discipline and possession time. Candidates also test scoring, Elo, recent form, schedule strength, experience, rest and passing/rushing interactions.</p><div className="formula">P(win) = w × logistic(β · x) + (1 − w) × logistic(scoring margin / 8)</div><p>Logistic regression minimizes training log loss plus an L2 penalty. Scales are fitted only on training years. Antisymmetric features and no intercept guarantee that swapping teams swaps win probabilities. No injuries, recruiting, transfers, EPA, weather or betting lines are inferred from missing data.</p><p>Neutral win index averages the selected model’s win probability against every other same-season FBS team on a neutral field, with equal rest. It ranks overall matchup strength. Scoring offense, defense and point projections remain an interpretable scoring component; they are not an additive explanation of the complete probability model.</p><p className="fine-print">Frozen search protocol SHA-256: {report.protocolSha256}</p></details>
 </section>
 <section className="surface"><h2>Probability calibration</h2><p className="subcopy">Predicted home-win probabilities versus observed outcomes. Bin sample sizes matter.</p><Table><TableHeader><TableRow>{['Probability bin','Games','Mean forecast','Observed wins'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{bins.map(b=><TableRow key={b.i}><TableCell>{b.i*10}–{(b.i+1)*10}%</TableCell><TableCell>{b.n}</TableCell><TableCell>{b.n?pct(b.p):'—'}</TableCell><TableCell>{b.n?pct(b.y):'—'}</TableCell></TableRow>)}</TableBody></Table></section>
 <section className="surface ledger"><div className="panel-title"><h2>The prediction ledger</h2><Button variant="outline" onClick={()=>download(`filtered-predictions-${data.season}.csv`,rows)}>Export filtered</Button></div><div className="ledger-filters"><Input aria-label="Search prediction teams" placeholder="Search either team…" value={search} onChange={e=>{setSearch(e.target.value);setPage(0)}}/><Picker label="Show predictions" value={filter} onChange={v=>{setFilter(v);setPage(0)}} options={[{value:'all',label:'All predictions'},{value:'miss',label:'Incorrect picks'},{value:'upset',label:'Upsets under 35%'}]}/><span>{rows.length} games</span></div><Table><TableHeader><TableRow>{['Date','Matchup','Final score','Home win chance','Outcome'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.slice(current*30,(current+1)*30).map(p=><TableRow key={p.id}><TableCell>{dateLabel(p.date)}</TableCell><TableCell>{p.awayName}<small className="muted">{p.neutral?'vs.':'at'} {p.homeName}</small></TableCell><TableCell>{p.as}–{p.hs}</TableCell><TableCell>{pct(p.prob)}</TableCell><TableCell>{(p.prob>=.5)===Boolean(p.outcome)?'Correct':'Miss'}</TableCell></TableRow>)}</TableBody></Table>{!rows.length&&<p className="empty">No predictions match these filters.</p>}<div className="ledger-filters"><Button variant="outline" disabled={current===0} onClick={()=>setPage(current-1)}>Previous</Button><span>{current+1} / {maxPage+1}</span><Button variant="outline" disabled={current===maxPage} onClick={()=>setPage(current+1)}>Next</Button></div></section>
 </>;
}
