"use client";
import {useEffect,useState} from 'react';
import {asset} from '@/lib/paths';
import {pct,download,Picker,dateLabel} from './ui';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Table,TableHeader,TableBody,TableHead,TableRow,TableCell} from '@/components/ui/table';
import type {Season} from './types';

type Scores={n:number;accuracy:number;brier:number;logLoss:number};
type Rating={talentMode:string;talentPrior:number;weight:string;method:string;carry:number;lam:number;memory:number;decay:number};
type Candidate=Scores&{passerTreatment:string;ratingConfig:Rating;bundle:string;ridge:number};
type FpiRow={id:string;name:string;rank:number;fpi:number;previousRank:number;v5Rank?:number;modelRank:number;gap:number};
type CurrentAnnual={selected:{bundle:string;ridge:number;indices:number[]};validationYears:number[];trainingThrough:number};
type Stability={promotionGate:{pooledLogLossImprovement:number;pooledAccuracyDelta:number;completeSeasonGuard:boolean;passed:boolean;bootstrap:{blocks:number;repetitions:number;probabilityLowerLogLoss:number;meanDelta:number;p05:number;p95:number}};pooled2024To2025:{candidate:Scores;v5:Scores};scope:string};
type ModelReport={cohortAblation:{targetSeason:number;mode:string;bestValidationLogLoss:number;candidates:number}[];passerCoverage:{season:number;validatedTeamGameGroups:number;rejectedTeamGameGroups:number}[];firstStageEvaluation:(Scores&{season:number})[];candidateCount:number;scope:string;protocolSha256:string;annual:Record<string,{selected:Candidate;validationYears:number[];trainingThrough:number}>;currentAnnual?:Record<string,CurrentAnnual>;stabilityResearch:Stability;searches:{targetSeason:number;candidates:Candidate[]}[];evaluation:(Scores&{season:number;model:string})[];coverage:{year:number;games:number;epaPairedGames:number;talentTeams:number;teams:number}[];fpiComparison:{note:string;excludedFlaggedRows:number;matchedGames:{season:number;n:number;fpiPickAccuracy:number|null;newAccuracy:number|null;previousAccuracy:number|null;originalAccuracy:number|null;v3Accuracy:number|null}[];rankMetrics:Record<string,{meanAbsoluteRankGap:number;spearman:number}>;teams:FpiRow[]}};
const percent=(n:number)=>`${(n*100).toFixed(2)}%`;
export function ModelAudit({data}:{data:Season}){
 const [report,setReport]=useState<ModelReport|null>(null),[error,setError]=useState(false),[search,setSearch]=useState(''),[filter,setFilter]=useState('all'),[page,setPage]=useState(0),[fpiSearch,setFpiSearch]=useState('');
 useEffect(()=>{let active=true;fetch(asset('/data/model.json')).then(r=>{if(!r.ok)throw Error();return r.json()}).then(d=>{if(active)setReport(d as ModelReport)}).catch(()=>{if(active)setError(true)});return()=>{active=false}},[]);
 if(!report)return <section className="surface"><h2>The model audit</h2><p>{error?'Research data could not load. Refresh to retry.':'Loading the validation evidence...'}</p></section>;
 const annual=report.currentAnnual?.[String(data.season)],evaluation=report.evaluation.filter(r=>r.season===data.season),gate=report.stabilityResearch.promotionGate;
 const rows=data.predictions.filter(p=>`${p.homeName} ${p.awayName}`.toLowerCase().includes(search.toLowerCase())&&(filter==='all'||filter==='miss'&&(p.prob>=.5)!==Boolean(p.outcome)||filter==='upset'&&(p.outcome?p.prob:1-p.prob)<.35));
 const maxPage=Math.max(0,Math.ceil(rows.length/30)-1),current=Math.min(page,maxPage);
 const bins=Array.from({length:10},(_,i)=>{const rr=data.predictions.filter(p=>Math.min(9,Math.floor(p.prob*10))===i);return {i,n:rr.length,p:rr.length?rr.reduce((s,r)=>s+r.prob,0)/rr.length:0,y:rr.length?rr.reduce((s,r)=>s+r.outcome,0)/rr.length:0}});
 const fpi=report.fpiComparison,fp= fpi.matchedGames.find(r=>r.season===data.season),gapRows=[...fpi.teams].filter(t=>t.name.toLowerCase().includes(fpiSearch.toLowerCase())).sort((a,b)=>Math.abs(b.gap)-Math.abs(a.gap));
 return <>
 <div className="section-heading"><div><h1>Model performance</h1><p>One team-strength score, updated by opponent-adjusted game evidence.</p></div><Button variant="outline" onClick={()=>download(`model-predictions-${data.season}.csv`,data.predictions)}>Export season predictions</Button></div>
 <section className="surface"><h2>Preseason is a starting point</h2><p>The model puts recruiting information inside the preseason scoring prior. Games then update that prior through opponent-adjusted scoring, first-down creation, passing, rushing and yards-per-play ratings. There is no separate weekly talent bonus.</p><details><summary>What we tested</summary><p>Six documented stages cover recruiting carryover, roster cohorts, observed passer history, raw pregame play features and a final opponent-adjusted replication. The raw success-rate result was not promoted until its signal survived explicit schedule-strength adjustment.</p><p>Each team has one neutral-field strength. Selection uses earlier-year log loss and never targets a desired rank for any school.</p><Table><TableHeader><TableRow>{['First experiment','Games','Accuracy','Log loss'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{report.firstStageEvaluation.map(r=><TableRow key={r.season}><TableCell>{r.season}</TableCell><TableCell>{r.n}</TableCell><TableCell>{percent(r.accuracy)}</TableCell><TableCell>{r.logLoss.toFixed(4)}</TableCell></TableRow>)}</TableBody></Table><p>Research files: <a href={asset('/data/research-stage1.json')} download>Stage 1</a> / <a href={asset('/data/research-stage2.json')} download>Stage 2</a> / <a href={asset('/data/research-stage3.json')} download>Stage 3</a> / <a href={asset('/data/research-stage5.json')} download>Raw pregame features</a> / <a href={asset('/data/research-stage6.json')} download>Opponent-adjusted replication</a>.</p></details><p className="callout">These are retrospective experiments on inspected seasons. The partial 2026 season is reported, but the promotion rule is based on the two complete 2024–2025 seasons.</p>
 {annual?<><div className="timeline"><div><strong>{annual.validationYears.join(' / ')}</strong><span>Inner validation seasons</span></div><div><strong>Through {annual.trainingThrough}</strong><span>Final coefficient training</span></div><div><strong>{data.season}</strong><span>Outer evaluation season</span></div></div><p>Selected: <strong>{annual.selected.bundle.replaceAll('_',' ')}</strong>, regression penalty {annual.selected.ridge}. All component ratings use the same prior-games-only snapshot and opponent adjustment.</p></>:<p>2018-2022 retain exploratory archive forecasts. Redesigned annual selection begins in 2023.</p>}
 <h3>Same games, four generations</h3><p className="subcopy">Full selected season, regardless of the week selector. Lower Brier and log loss are better. 2026 is partial, through September 20.</p><Table><TableHeader><TableRow>{['Model','Games','Accuracy','Brier','Log loss'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{evaluation.map(r=><TableRow key={r.model}><TableCell>{r.model}</TableCell><TableCell>{r.n}</TableCell><TableCell>{percent(r.accuracy)}</TableCell><TableCell>{r.brier.toFixed(4)}</TableCell><TableCell>{r.logLoss.toFixed(4)}</TableCell></TableRow>)}</TableBody></Table>
 <h3>Why v6 passed the promotion gate</h3><Table><TableHeader><TableRow>{['2024–2025 pooled','V6','V5','Change'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody><TableRow><TableCell>Log loss</TableCell><TableCell>{report.stabilityResearch.pooled2024To2025.candidate.logLoss.toFixed(5)}</TableCell><TableCell>{report.stabilityResearch.pooled2024To2025.v5.logLoss.toFixed(5)}</TableCell><TableCell>{(-gate.pooledLogLossImprovement).toFixed(5)}</TableCell></TableRow><TableRow><TableCell>Winner accuracy</TableCell><TableCell>{percent(report.stabilityResearch.pooled2024To2025.candidate.accuracy)}</TableCell><TableCell>{percent(report.stabilityResearch.pooled2024To2025.v5.accuracy)}</TableCell><TableCell>{gate.pooledAccuracyDelta>=0?'+':''}{(gate.pooledAccuracyDelta*100).toFixed(2)} pp</TableCell></TableRow></TableBody></Table><p className="fine-print">Week-block bootstrap: {(gate.bootstrap.probabilityLowerLogLoss*100).toFixed(1)}% of 10,000 resamples favored v6 across {gate.bootstrap.blocks} weeks. The prespecified threshold was 90%. Both complete-season protection checks passed.</p>
 </section>
 <section className="surface"><h2>ESPN as an external benchmark</h2><p>We use ESPN&apos;s published approach as methodological guidance and its dated FPI snapshots as a comparison. ESPN&apos;s full proprietary formula is unavailable. Our EPA comes from the public cfbfastR pipeline and is not ESPN&apos;s proprietary EPA.</p>
 <h3>Historical FPI-based picks, matched to the same games</h3><p className="subcopy">Only snapshots timestamped before the frozen prediction week qualify. The benchmark picks the team favored by FPI difference plus a fixed three-point home adjustment. These are our FPI-based picks, not ESPN&apos;s official game probabilities.</p>
 {fp&&fp.n>0?<Table><TableHeader><TableRow>{['Matched games','FPI-based accuracy','Archived v5','Previous v4'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody><TableRow><TableCell>{fp.n}</TableCell><TableCell>{percent(fp.fpiPickAccuracy!)}</TableCell><TableCell>{percent(fp.newAccuracy!)}</TableCell><TableCell>{percent(fp.previousAccuracy!)}</TableCell></TableRow></TableBody></Table>:<p>No matched FPI comparison for this season.</p>}
 <p className="fine-print">Rejected {fpi.excludedFlaggedRows.toLocaleString()} flagged or undated archive rows before matching. A week label alone is not sufficient: some early-week rows contain end-of-season updates. <a href={asset('/data/fpi-paired-audit.json')} download>Download timestamp audit</a>.</p>
 <h3>Whole-field ranking agreement</h3><p>Fixed comparison: model results through September 20, 2026 versus FPI updated September 22. Independent of the selector above; not an exact same-time comparison.</p><Table><TableHeader><TableRow>{['Ranking','Mean absolute rank gap','Spearman correlation'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{[['previous','Previous v4'],['new','Previous v5'],['current','Current v6']].filter(([key])=>fpi.rankMetrics[key]).map(([key,label])=><TableRow key={key}><TableCell>{label}</TableCell><TableCell>{fpi.rankMetrics[key].meanAbsoluteRankGap.toFixed(2)}</TableCell><TableCell>{fpi.rankMetrics[key].spearman.toFixed(3)}</TableCell></TableRow>)}</TableBody></Table><p><a href="https://www.espn.co.uk/college-football/fpi/_/season/2026" target="_blank" rel="noreferrer">ESPN FPI source</a></p>
 <details><summary>Inspect all {fpi.teams.length} teams, largest disagreements first</summary><Input aria-label="Search FPI comparison" placeholder="Find a team in the FPI comparison..." value={fpiSearch} onChange={e=>setFpiSearch(e.target.value)}/><Table><TableHeader><TableRow>{['Team','FPI rank','V5 rank','V6 rank','V6 minus FPI'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{gapRows.map(t=><TableRow key={t.id}><TableCell>{t.name}</TableCell><TableCell>{t.rank}</TableCell><TableCell>{t.v5Rank??t.previousRank}</TableCell><TableCell>{t.modelRank}</TableCell><TableCell>{t.gap}</TableCell></TableRow>)}</TableBody></Table></details></section>
 <section className="surface"><h2>Coverage is part of the model</h2><p>Missing efficiency pairs are omitted from unit fits. Recruiting talent is standardized by season. Actual passers in the most recent completed game link to their previous-season FBS passing records; this is observed context, not a confirmed future starter or injury report.</p><p className="fine-print">{report.scope}</p><details><summary>View source coverage and research files</summary><Table><TableHeader><TableRow>{['Season','FBS games','Paired EPA games','Talent teams / FBS teams'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{report.coverage.map(c=><TableRow key={c.year}><TableCell>{c.year}</TableCell><TableCell>{c.games}</TableCell><TableCell>{c.epaPairedGames}</TableCell><TableCell>{c.talentTeams} / {c.teams}</TableCell></TableRow>)}</TableBody></Table><h3>Passing-box validation</h3><Table><TableHeader><TableRow><TableHead>Season</TableHead><TableHead>Validated team-game groups</TableHead><TableHead>Rejected groups</TableHead></TableRow></TableHeader><TableBody>{report.passerCoverage.map(c=><TableRow key={c.season}><TableCell>{c.season}</TableCell><TableCell>{c.validatedTeamGameGroups}</TableCell><TableCell>{c.rejectedTeamGameGroups}</TableCell></TableRow>)}</TableBody></Table><p><a href={asset('/data/model.json')} download>Complete report</a> / <a href={asset('/data/model-v5.json')} download>Archived v5</a> / <a href={asset('/data/model-v4.json')} download>Archived v4</a> / <a href={asset('/data/model-v3.json')} download>Archived v3</a></p><p className="fine-print">Protocol SHA-256: {report.protocolSha256}</p></details></section>
 <section className="surface"><h2>Probability calibration</h2><p className="subcopy">Predicted home-win probabilities versus observed outcomes; small bins are uncertain.</p><Table><TableHeader><TableRow>{['Probability bin','Games','Mean forecast','Observed wins'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{bins.map(b=><TableRow key={b.i}><TableCell>{b.i*10}-{(b.i+1)*10}%</TableCell><TableCell>{b.n}</TableCell><TableCell>{b.n?pct(b.p):'Unavailable'}</TableCell><TableCell>{b.n?pct(b.y):'Unavailable'}</TableCell></TableRow>)}</TableBody></Table></section>
 <section className="surface ledger"><div className="panel-title"><h2>The prediction ledger</h2><Button variant="outline" onClick={()=>download(`filtered-predictions-${data.season}.csv`,rows)}>Export filtered</Button></div><div className="ledger-filters"><Input aria-label="Search prediction teams" placeholder="Search either team..." value={search} onChange={e=>{setSearch(e.target.value);setPage(0)}}/><Picker label="Show predictions" value={filter} onChange={v=>{setFilter(v);setPage(0)}} options={[{value:'all',label:'All predictions'},{value:'miss',label:'Incorrect picks'},{value:'upset',label:'Upsets under 35%'}]}/><span>{rows.length} games</span></div><Table><TableHeader><TableRow>{['Date','Matchup','Final score','Home win chance','Outcome'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.slice(current*30,(current+1)*30).map(p=><TableRow key={p.id}><TableCell>{dateLabel(p.date)}</TableCell><TableCell>{p.awayName}<small className="muted">{p.neutral?'vs.':'at'} {p.homeName}</small></TableCell><TableCell>{p.as}-{p.hs}</TableCell><TableCell>{pct(p.prob)}</TableCell><TableCell>{(p.prob>=.5)===Boolean(p.outcome)?'Correct':'Miss'}</TableCell></TableRow>)}</TableBody></Table>{!rows.length&&<p className="empty">No predictions match these filters.</p>}<div className="ledger-filters"><Button variant="outline" disabled={current===0} onClick={()=>setPage(current-1)}>Previous</Button><span>{current+1} / {maxPage+1}</span><Button variant="outline" disabled={current===maxPage} onClick={()=>setPage(current+1)}>Next</Button></div></section>
 </>;
}
