"use client";
import {useEffect,useMemo,useState} from 'react';
import {ArrowDownToLine,Search,ArrowUpRight} from 'lucide-react';
import {Table,TableHeader,TableBody,TableHead,TableRow,TableCell} from '@/components/ui/table';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Input} from '@/components/ui/input';
import {Button} from '@/components/ui/button';
import type {Team,Season,Manifest,Report} from './types';
import {Picker,Logo,signed,pct,dateLabel,weekName,download} from './ui';
import {Scouting} from './scouting';
import {Matchup} from './matchup';
import {ModelAudit} from './model-audit';
import {Methodology} from './methodology';
import {StrengthMap} from './strength-map';
import {RankTrends} from './rank-trends';
import {asset} from '@/lib/paths';

export default function Home(){
  const [manifest,setManifest]=useState<Manifest|null>(null),[report,setReport]=useState<Report|null>(null),[data,setData]=useState<Season|null>(null);
  const [advanced,setAdvanced]=useState(false),[showAll,setShowAll]=useState(false);
  const [season,setSeason]=useState('2026'),[week,setWeek]=useState('99'),[view,setView]=useState('rankings'),[search,setSearch]=useState(''),[conference,setConference]=useState('all'),[sort,setSort]=useState('winIndex'),[error,setError]=useState(''),[loading,setLoading]=useState(true),[selected,setSelected]=useState('194');
  useEffect(()=>{Promise.all([fetch(asset('/data/manifest.json')).then(r=>r.json()),fetch(asset('/data/report.json')).then(r=>r.json())]).then(([m,r])=>{setManifest(m as Manifest);setReport(r as Report)}).catch(()=>setError('Data could not load. Refresh this page to try again.'))},[]);
  useEffect(()=>{const c=new AbortController();fetch(asset(`/data/${season}.json`),{signal:c.signal}).then(r=>{if(!r.ok)throw Error();return r.json()}).then(d=>{setData(d as Season);setWeek('99');setShowAll(false);setLoading(false)}).catch(e=>{if(e.name!=='AbortError'){setError('This season could not load. Choose another season or refresh.');setLoading(false)}});return()=>c.abort()},[season]);
  const snapshot=data?.snapshots[week],teams=useMemo(()=>snapshot?.teams??[],[snapshot]);
  const visible=useMemo(()=>teams.filter(t=>(conference==='all'||t.conference===conference)&&`${t.name} ${t.abbr}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>Number(b[sort as keyof Team]??(sort==='winIndex'?b.power:-999))-Number(a[sort as keyof Team]??(sort==='winIndex'?a.power:-999))),[teams,conference,search,sort]);
  const isFiltered=Boolean(search)||conference!=='all'||sort!=='winIndex',displayed=showAll||isFiltered?visible:visible.slice(0,25);
  const openTeam=(id:string)=>{setSelected(id);setView('teams')};
  useEffect(()=>{const context=(document as unknown as {modelContext?:{registerTool:(t:unknown,o:{signal:AbortSignal})=>unknown}}).modelContext;if(!context?.registerTool||!snapshot)return;const life=new AbortController();const register=(tool:unknown)=>{try{Promise.resolve(context.registerTool(tool,{signal:life.signal})).catch(()=>{})}catch{}};register({name:'get_football_rankings',description:'Read the current season and week model rankings and neutral win indices.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({season:Number(season),week:Number(week),teams:snapshot.teams.map(t=>({id:t.id,name:t.name,rank:t.modelRank??t.rank,winIndex:t.winIndex??null,scoringPower:t.power}))})});register({name:'open_team_report',description:'Open a team scouting report in the current season and week.',inputSchema:{type:'object',properties:{teamId:{type:'string'}},required:['teamId'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:unknown)=>{const id=(input as {teamId?:string})?.teamId;if(!id||!snapshot.teams.some(t=>t.id===id))throw new Error('Unknown team ID for the current season.');setSelected(id);setView('teams');await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));return {opened:true,teamId:id,season:Number(season),week:Number(week)}}});return()=>life.abort()},[snapshot,season,week]);
  return <div className="site-shell"><header className="masthead"><a className="brand" href={asset('/')} aria-label="Saturday Lab home"><span className="brand-mark">S<span>L</span></span><span>Saturday<span className="brand-light"> Lab</span><small>College football, measured.</small></span></a><div className="masthead-note"><span>2026 FBS DATA DESK</span><strong>Rankings, team reports and game forecasts</strong></div><a className="source-link" href="https://github.com/heimweh17/saturday-lab" target="_blank" rel="noreferrer">About this project <ArrowUpRight size={16}/></a></header>
    <Tabs value={view} onValueChange={setView} className="app-tabs"><div className="nav-wrap"><TabsList className="main-nav" variant="line"><TabsTrigger value="rankings">Rankings</TabsTrigger><TabsTrigger value="teams">Teams</TabsTrigger><TabsTrigger value="matchup">Matchup</TabsTrigger><TabsTrigger value="trends">Rank trends</TabsTrigger><span className="nav-divider" aria-hidden="true"/><TabsTrigger value="backtest" className="secondary-nav">Model audit</TabsTrigger><TabsTrigger value="method" className="secondary-nav">Methodology</TabsTrigger></TabsList><span className="nav-meta">MODEL v{manifest?.version?.split('.')[0]??'6'}</span></div>
    <main>{view!=='method'&&<div className="context-toolbar"><div className="context-pickers"><Picker label="Season" value={season} onChange={v=>{setLoading(true);setError('');setSeason(v);setConference('all')}} options={(manifest?.seasons??[2026]).slice().reverse().map(y=>({value:String(y),label:String(y)}))}/>{view!=='backtest'&&<Picker label="Snapshot" value={week} onChange={setWeek} options={(data?.weeks??[99]).map(w=>({value:String(w),label:weekName(w)}))}/>}</div>{view!=='backtest'&&<div className="snapshot-note"><span className="small-rule"/>Results through <strong>{dateLabel(snapshot?.through??null)}</strong><span>Saved snapshot</span></div>}</div>}
    {error?<div className="notice" role="alert">{error}</div>:loading||!snapshot?<div className="loading" role="status">Loading football data…</div>:<>
      <TabsContent value="rankings"><div className="section-heading rankings-heading"><div><span className="scoreline">{season} FBS · {weekName(Number(week))}</span><h1>National power rankings</h1><p>Opponent-adjusted team strength and neutral-field win index. Open any team for its schedule, results and forecast.</p></div><Button variant="outline" onClick={()=>download(`saturday-rankings-${season}-${week}.csv`,visible)}><ArrowDownToLine size={16}/> Export</Button></div>
      <div className="data-dashboard"><section className="ranking-panel"><div className="table-controls"><div className="search-wrap"><Search size={17}/><Input aria-label="Find a team" placeholder="Search teams…" value={search} onChange={e=>setSearch(e.target.value)}/></div><Picker label="Conference" value={conference} onChange={setConference} options={[{value:'all',label:'All conferences'},...Array.from(new Set(teams.map(t=>t.conference))).sort().map(c=>({value:c,label:c.replace(' Conference','')}))]}/></div><div className="ranking-options"><span>{isFiltered?`${visible.length} teams`:'Top 25'} · strength index is average neutral win chance vs. the FBS field</span><Button variant="outline" aria-pressed={advanced} onClick={()=>{setAdvanced(!advanced);setSort('winIndex')}}>{advanced?'Fewer columns':'More stats'}</Button></div><Table><TableHeader><TableRow><TableHead>Rank</TableHead><TableHead>Team</TableHead>{(advanced?[['winIndex','Strength'],['power','Scoring'],['offense','Offense'],['defense','Defense'],['sos','Schedule']]:[['winIndex','Strength']]).map(([k,l])=><TableHead key={k}><button className={sort===k?'sort-active':''} onClick={()=>setSort(k)} title={`Sort by ${l}, highest first`}>{l}{sort===k?' ↓':''}</button></TableHead>)}</TableRow></TableHeader><TableBody>{displayed.map(t=><TableRow key={t.id}><TableCell><span className="rank-number">{t.modelRank??t.rank}</span><small className={(t.modelChange??t.change)>0?'positive':(t.modelChange??t.change)<0?'negative':'muted'}>{(t.modelChange??t.change)?`${(t.modelChange??t.change)>0?'↑':'↓'}${Math.abs(t.modelChange??t.change)}`:'—'}</small></TableCell><TableCell><button className="team-cell" onClick={()=>openTeam(t.id)}><Logo team={t}/><span><strong>{t.short}</strong><small>{t.wins}–{t.losses} <span className="conference-tiny">{t.conference.replace(' Conference','')}</span></small></span></button></TableCell><TableCell className="power-number">{pct(t.winIndex)}</TableCell>{advanced&&<><TableCell>{signed(t.power)}</TableCell><TableCell>{signed(t.offense)}</TableCell><TableCell>{signed(t.defense)}</TableCell><TableCell>{signed(t.sos)}</TableCell></>}</TableRow>)}</TableBody></Table>{!displayed.length&&<div className="empty">No teams match. Try another name or conference.</div>}{!isFiltered&&visible.length>25&&<button className="show-all-rankings" onClick={()=>setShowAll(!showAll)}>{showAll?'Show Top 25':`Show all ${visible.length} FBS teams`}</button>}<p className="table-foot">Strength is a modeled probability, not the chance of winning the next scheduled game. Select a team to see game-specific forecasts.</p></section>
      <aside className="dashboard-rail"><div className="quick-stat"><span>FIELD</span><strong>{teams.length}</strong><small>rated FBS teams</small></div><div className="quick-stat"><span>GAMES USED</span><strong>{snapshot.modelGames}</strong><small>FBS matchups in snapshot</small></div><button className="rail-action" onClick={()=>setView('trends')}><strong>Compare rank movement</strong><span>Follow up to 12 teams across the season →</span></button><button className="rail-action" onClick={()=>setView('matchup')}><strong>Build a matchup</strong><span>Change teams and venue →</span></button></aside></div><StrengthMap teams={visible} onSelect={openTeam}/></TabsContent>
      <TabsContent value="teams">{data&&report&&<Scouting key={season} config={report.config} data={data} snapshot={snapshot} week={week} selected={selected} onSelect={setSelected} onCompare={id=>{setSelected(id);setView('matchup')}}/>}</TabsContent>
      <TabsContent value="matchup">{data&&report&&<Matchup key={`${season}-${selected}`} data={data} snapshot={snapshot} report={report} initial={selected} week={week}/>}</TabsContent>
      <TabsContent value="trends">{data&&<RankTrends key={season} data={data} onOpenTeam={openTeam}/>}</TabsContent>
      <TabsContent value="backtest">{data&&report&&<ModelAudit key={season} data={data}/>}</TabsContent><TabsContent value="method">{manifest&&report&&<Methodology manifest={manifest} report={report}/>}</TabsContent>
    </>}</main></Tabs><footer><span>Saturday Lab</span><p>Independent college football analytics. Not affiliated with the NCAA, ESPN or any university.</p><span>MODEL v{manifest?.version?.split('.')[0]??'6'} · DATED SNAPSHOTS</span></footer></div>;
}
