"use client";
import {useEffect,useMemo,useState} from 'react';
import {useRouter} from 'next/navigation';
import {ArrowDownToLine,Search} from 'lucide-react';
import {Table,TableHeader,TableBody,TableHead,TableRow,TableCell} from '@/components/ui/table';
import {Input} from '@/components/ui/input';
import {Button} from '@/components/ui/button';
import type {Team,Season,Manifest} from './types';
import {Picker,Logo,signed,pct,dateLabel,weekName,download} from './ui';
import {StrengthMap} from './strength-map';
import {GameStrip} from './game-strip';
import {SnapshotPulse} from './snapshot-pulse';
import {asset} from '@/lib/paths';
import {gamePath,teamPath} from '@/lib/routes';

export default function Home(){
  const router=useRouter();
  const [manifest,setManifest]=useState<Manifest|null>(null),[data,setData]=useState<Season|null>(null);
  const [advanced,setAdvanced]=useState(false),[showAll,setShowAll]=useState(false);
  const [season,setSeason]=useState('2026'),[week,setWeek]=useState('99'),[search,setSearch]=useState(''),[conference,setConference]=useState('all'),[sort,setSort]=useState('winIndex'),[error,setError]=useState('');
  useEffect(()=>{fetch(asset('/data/manifest.json')).then(r=>r.json()).then(m=>setManifest(m as Manifest)).catch(()=>setError('Data could not load. Refresh this page to try again.'))},[]);
  useEffect(()=>{const c=new AbortController();fetch(asset(`/data/${season}.json`),{signal:c.signal}).then(r=>{if(!r.ok)throw Error();return r.json()}).then(d=>{setData(d as Season);setWeek('99');setShowAll(false)}).catch(e=>{if(e.name!=='AbortError')setError('This season could not load. Choose another season or refresh.')});return()=>c.abort()},[season]);
  const currentData=data?.season===Number(season)?data:null,snapshot=currentData?.snapshots[week],teams=useMemo(()=>snapshot?.teams??[],[snapshot]);
  const visible=useMemo(()=>teams.filter(t=>(conference==='all'||t.conference===conference)&&`${t.name} ${t.abbr}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>Number(b[sort as keyof Team]??(sort==='winIndex'?b.power:-999))-Number(a[sort as keyof Team]??(sort==='winIndex'?a.power:-999))),[teams,conference,search,sort]);
  const isFiltered=Boolean(search)||conference!=='all'||sort!=='winIndex',displayed=showAll||isFiltered?visible:visible.slice(0,25);
  const openTeam=(id:string)=>{const team=teams.find(t=>t.id===id);if(team)router.push(teamPath(team))};
  useEffect(()=>{const context=(document as unknown as {modelContext?:{registerTool:(t:unknown,o:{signal:AbortSignal})=>unknown}}).modelContext;if(!context?.registerTool||!snapshot)return;const life=new AbortController();try{Promise.resolve(context.registerTool({name:'get_football_rankings',description:'Read the current season and week model rankings and neutral win indices.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({season:Number(season),week:Number(week),teams:snapshot.teams.map(t=>({id:t.id,name:t.name,rank:t.modelRank??t.rank,winIndex:t.winIndex??null,scoringPower:t.power}))})},{signal:life.signal})).catch(()=>{})}catch{}return()=>life.abort()},[snapshot,season,week]);
  return <>{currentData&&<GameStrip data={currentData} onOpenTeam={openTeam} onOpenMatchup={game=>{if(game.fixtureId&&game.awayName&&game.homeName)router.push(gamePath({id:game.fixtureId,season:currentData.season,awayName:game.awayName,homeName:game.homeName,neutral:Boolean(game.neutral)}))}}/>}<main><div className="context-toolbar"><div className="context-pickers"><Picker label="Season" value={season} onChange={v=>{setError('');setSeason(v);setConference('all')}} options={(manifest?.seasons??[2026]).slice().reverse().map(y=>({value:String(y),label:String(y)}))}/><Picker label="Snapshot" value={week} onChange={setWeek} options={(currentData?.weeks??[99]).map(w=>({value:String(w),label:weekName(w)}))}/></div><div className="snapshot-note"><span className="small-rule"/>Results through <strong>{dateLabel(snapshot?.through??null)}</strong><span>Saved snapshot</span></div></div>
  {error?<div className="notice" role="alert">{error}</div>:!snapshot?<div className="loading" role="status">Loading football data…</div>:<div data-slot="tabs-content" className="rankings-route"><div className="section-heading rankings-heading"><div><span className="scoreline">SATURDAY LAB POWER INDEX · {weekName(Number(week))}</span><h1>The national board</h1><p>How every FBS team rates right now, after adjusting each performance for the opponent across the field.</p></div><div className="heading-stamp"><strong>{dateLabel(snapshot.through)}</strong><span>LAST RESULTS INCLUDED</span></div><Button variant="outline" onClick={()=>download(`saturday-rankings-${season}-${week}.csv`,visible)}><ArrowDownToLine size={16}/> Export</Button></div>
  <div className="data-dashboard"><section className="ranking-panel"><div className="table-controls"><div className="search-wrap"><Search size={17}/><Input aria-label="Find a team" placeholder="Search teams…" value={search} onChange={e=>setSearch(e.target.value)}/></div><Picker label="Conference" value={conference} onChange={setConference} options={[{value:'all',label:'All conferences'},...Array.from(new Set(teams.map(t=>t.conference))).sort().map(c=>({value:c,label:c.replace(' Conference','')}))]}/></div><div className="ranking-options"><span>{isFiltered?`${visible.length} teams`:'Top 25'} · strength index is average neutral win chance vs. the FBS field</span><Button variant="outline" aria-pressed={advanced} onClick={()=>{setAdvanced(!advanced);setSort('winIndex')}}>{advanced?'Fewer columns':'More stats'}</Button></div><Table><TableHeader><TableRow><TableHead>Rank</TableHead><TableHead>Team</TableHead>{(advanced?[['winIndex','Strength'],['power','Scoring'],['offense','Offense'],['defense','Defense'],['sos','Schedule']]:[['winIndex','Strength']]).map(([k,l])=><TableHead key={k}><button className={sort===k?'sort-active':''} onClick={()=>setSort(k)} title={`Sort by ${l}, highest first`}>{l}{sort===k?' ↓':''}</button></TableHead>)}</TableRow></TableHeader><TableBody>{displayed.map(t=><TableRow key={t.id}><TableCell><span className="rank-number">{t.modelRank??t.rank}</span><small className={(t.modelChange??t.change)>0?'positive':(t.modelChange??t.change)<0?'negative':'muted'}>{(t.modelChange??t.change)?`${(t.modelChange??t.change)>0?'↑':'↓'}${Math.abs(t.modelChange??t.change)}`:'—'}</small></TableCell><TableCell><button className="team-cell" onClick={()=>openTeam(t.id)}><Logo team={t}/><span><strong>{t.short}</strong><small>{t.wins}–{t.losses} <span className="conference-tiny">{t.conference.replace(' Conference','')}</span></small></span></button></TableCell><TableCell className="power-number">{pct(t.winIndex)}</TableCell>{advanced&&<><TableCell>{signed(t.power)}</TableCell><TableCell>{signed(t.offense)}</TableCell><TableCell>{signed(t.defense)}</TableCell><TableCell>{signed(t.sos)}</TableCell></>}</TableRow>)}</TableBody></Table>{!displayed.length&&<div className="empty">No teams match. Try another name or conference.</div>}{!isFiltered&&visible.length>25&&<button className="show-all-rankings" onClick={()=>setShowAll(!showAll)}>{showAll?'Show Top 25':`Show all ${visible.length} FBS teams`}</button>}<p className="table-foot">Strength is a modeled probability, not the chance of winning the next scheduled game. Select a team to open its permanent report page.</p></section><SnapshotPulse teams={teams} onSelect={openTeam} onTrends={()=>router.push('/rank-trends/')}/></div><StrengthMap teams={visible} onSelect={openTeam}/></div>}</main></>;
}
