"use client";
/* eslint-disable react/no-unescaped-entities */
import {useState} from 'react';
import type {CSSProperties} from 'react';
import {ArrowDownToLine} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Table,TableHeader,TableBody,TableHead,TableRow,TableCell} from '@/components/ui/table';
import {Picker,Logo,signed,fixed,pct,dateLabel,download} from './ui';
import {DataExplorer} from './data-explorer';
import {RankHistory} from './rank-history';
import {Forecast} from './forecast';
import type {Season,Snapshot,Config} from './types';
export function Scouting({data,snapshot,week,selected,onSelect,onCompare,config}:{config:Config;data:Season;snapshot:Snapshot;week:string;selected:string;onSelect:(v:string)=>void;onCompare:(v:string)=>void}){
const [section,setSection]=useState('overview');const [split,setSplit]=useState('all');const team=snapshot.teams.find(t=>t.id===selected)??snapshot.teams[0];
const cutoff=data.weeks.indexOf(Number(week));const allowed=new Set(data.weeks.slice(0,cutoff));
const games=data.games.filter(g=>allowed.has(g.week)&&(g.home===team.id||g.away===team.id));
const filtered=games.filter(g=>split==='all'||split==='fbs'&&g.fbs||split==='home'&&!g.neutral&&g.home===team.id||split==='away'&&!g.neutral&&g.away===team.id||split==='neutral'&&g.neutral);
const trend=data.weeks.slice(0,cutoff+1).map(w=>({week:w,team:data.snapshots[String(w)].teams.find(t=>t.id===team.id)})).filter(x=>x.team);
const max=Math.max(20,...trend.map(t=>Math.abs(t.team!.power)))+3;const tx=(i:number)=>42+i/Math.max(1,trend.length-1)*670;const ty=(v:number)=>125-v/max*85;
const options=snapshot.teams.slice().sort((a,b)=>a.name.localeCompare(b.name)).map(t=>({value:t.id,label:t.name}));
return <><div className="section-heading"><div><h1>Teams &amp; schedules</h1><p>Choose a team, then explore its season, upcoming games or detailed statistics.</p></div><Picker label="Team" value={team.id} onChange={onSelect} options={options}/></div><section className="team-banner" style={{'--team-color':team.color} as CSSProperties}><div className="team-identity"><Logo team={team} size={75}/><div><p>{team.conference}</p><h2>{team.name}</h2><span>{team.wins}–{team.losses} overall · {team.modelGames} FBS games in this season’s model</span></div></div><div className="team-national"><strong>#{team.modelRank??team.rank}</strong><span>National power rank</span></div><Button onClick={()=>onCompare(team.id)}>Compare a matchup</Button></section>
<nav className="team-sections" aria-label="Team report sections">{[['overview','Overview'],['upcoming','Upcoming games'],['results','Results'],['stats','Detailed stats']].map(([id,label])=><button key={id} aria-pressed={section===id} onClick={()=>setSection(id)}>{label}</button>)}</nav>
{section==='overview'&&<><RankHistory data={data} teamId={team.id} week={week}/><details className="advanced-details"><summary>Scoring ratings &amp; model inputs</summary><div className="stat-strip"><Stat label="Scoring power" value={signed(team.power)} note="Points vs. average FBS"/><Stat label="Adjusted offense" value={signed(team.offense)} note="Points added / game"/><Stat label="Adjusted defense" value={signed(team.defense)} note="Points prevented / game"/><Stat label="Schedule strength" value={signed(team.sos)} note="Mean opponent net rating"/></div>
{team.modelGames<4&&<p className="callout">Small sample: {team.modelGames} FBS games. The prior-year rating and shrinkage still have a meaningful influence. A low early-season rating is not a final verdict.</p>}
<div className="two-col"><section className="surface"><div className="panel-title"><h2>The scoring component, over time</h2><span className="muted">Power / points</span></div><svg viewBox="0 0 760 260" className="trend-chart" role="img" aria-label={`${team.short} power rating trend through the selected week`}>{[-20,-10,0,10,20].map(n=><g key={n}><line x1="42" x2="712" y1={ty(n)} y2={ty(n)} stroke="#dce5eb" strokeDasharray={n===0?'0':'4 5'}/><text x="30" y={ty(n)+4} textAnchor="end">{n}</text></g>)}<polyline points={trend.map((p,i)=>`${tx(i)},${ty(p.team!.power)}`).join(' ')} fill="none" stroke="#1768ac" strokeWidth="3"/>{trend.map((p,i)=><g key={p.week}><circle cx={tx(i)} cy={ty(p.team!.power)} r="4" fill="#1768ac"><title>{p.week===99?'Latest':`Before ${p.week>=30?'postseason '+(p.week-30):'week '+p.week}`}: {signed(p.team!.power)}, rank #{p.team!.modelRank??p.team!.rank}</title></circle>{(i===0||i===trend.length-1||i%3===0)&&<text x={tx(i)} y="240" textAnchor="middle">{p.week===99?'Latest':p.week>=30?'Post':'W'+p.week}</text>}</g>)}</svg><p className="fine-print">Each point uses only games completed before that week. The first point is the offseason prior.</p></section><section className="surface"><h2>Inside the box score</h2><p className="subcopy">Season-to-date averages, all opponents. {team.boxGames} box scores available.</p><dl className="stat-list">{[['Points scored',fixed(team.pf)],['Points allowed',fixed(team.pa)],['Total yards',fixed(team.yards)],['Passing / rushing yards',`${fixed(team.passYards)} / ${fixed(team.rushYards)}`],['Opponent yards',fixed(team.yardsAllowed)],['Third-down conversion',pct(team.thirdDown)],['Pass completion',pct(team.completion)],['Turnovers / takeaways',`${fixed(team.turnovers)} / ${fixed(team.takeaways)}`]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></section></div>
{team.modelState?.q&&<section className="surface"><h2>Model evidence at this snapshot</h2><p className="subcopy">Opponent-adjusted team ratings and observed passer history. Recruiting enters the preseason scoring prior rather than a separate weekly bonus.</p><dl className="stat-list"><div><dt>Net EPA per play</dt><dd>{team.modelState.q[1].toFixed(3)}</dd></div><div><dt>Net special-teams EPA per game</dt><dd>{team.modelState.q[2].toFixed(3)}</dd></div><div><dt>Results-based Elo</dt><dd>{(1500+team.modelState.q[3]*100).toFixed(1)}</dd></div><div><dt>Non-explosive net EPA / play</dt><dd>{team.modelState.q[6].toFixed(3)}</dd></div><div><dt>Adjusted turnover control</dt><dd>{signed(team.modelState.q[7],2)}</dd></div>{team.modelState.q.length>12&&<><div><dt>Adjusted first-down creation</dt><dd>{signed(team.modelState.q[8],3)}</dd></div><div><dt>Adjusted passing EPA</dt><dd>{signed(team.modelState.q[9],3)}</dd></div><div><dt>Adjusted rushing EPA</dt><dd>{signed(team.modelState.q[10],3)}</dd></div><div><dt>Adjusted yards per play</dt><dd>{signed(team.modelState.q[11],2)}</dd></div><div><dt>Adjusted explosive-play rate</dt><dd>{signed(team.modelState.q[12],3)}</dd></div></>}<div><dt>Recruiting proxy (standard deviations)</dt><dd>{team.modelState.talentMissing?'Unavailable; mean imputed':signed(team.modelState.q[4],2)}</dd></div><div><dt>Recruiting data coverage</dt><dd>{team.modelState.talentMissing?'Missing; FBS mean prior':'Available'}</dd></div>{team.modelState.passerContext&&<><div><dt>Observed passer’s prior efficiency</dt><dd>{team.modelState.passerContext.available?signed(team.modelState.passerContext.values[0],2):'Not yet observed'}</dd></div><div><dt>Passer context observed through</dt><dd>{dateLabel(team.modelState.passerContext.observedThrough)}</dd></div></>}</dl><p className="fine-print">These metrics have different units and do not add up to a points margin. Only inputs with nonzero fitted weights affect the published probability. Each efficiency rating adjusts for the opponents faced before this snapshot. Passer efficiency is previous-season adjusted yards per attempt above that season’s league mean, shrunk toward zero; zero can mean no prior FBS record.</p></section>}
{team.modelState?.v&&<section className="surface"><h2>Evidence beyond the final score</h2><p className="subcopy">Opponent-adjusted net unit ratings at this snapshot. EPA per play and special-teams EPA per game have different units; they are not additive point margins.</p><dl className="stat-list">{[['Net EPA / play',team.modelState.v[1]],['Net passing EPA / play',team.modelState.v[2]],['Net rushing EPA / play',team.modelState.v[3]],['Net special-teams EPA / game',team.modelState.v[4]],['Net yards / play',team.modelState.v[5]]].map(([label,value])=><div key={String(label)}><dt>{label}</dt><dd>{Number(value).toFixed(3)}</dd></div>)}<div><dt>Four-class recruiting composite</dt><dd>{team.modelState.talentMissing?'Unavailable (mean imputed)':(team.modelState.v[6]*1000).toFixed(1)}</dd></div><div><dt>Blue-chip share</dt><dd>{team.modelState.talentMissing?'Unavailable':pct(team.modelState.v[7])}</dd></div></dl><p className="fine-print">EPA source: SportsDataverse / cfbfastR. Recruiting is a signed-class proxy, not a transfer-adjusted roster. Unit ratings include preseason shrinkage; missing game pairs are omitted. Displayed candidate metrics are not necessarily all selected in this season's probability model.</p></section>}
</details></>}
{section==='upcoming'&&<Forecast data={data} teamId={team.id} config={config}/>}
{section==='stats'&&<DataExplorer data={data} snapshot={snapshot} week={week} teamId={team.id}/>}
{section==='results'&&<section className="surface ledger"><div className="panel-title"><div><h2>Completed games</h2><p className="subcopy">Completed games through the selected snapshot. Reconstructed pregame estimates use only earlier weeks’ results; the research is retrospective.</p></div><Button variant="outline" onClick={()=>download(`${team.abbr}-${data.season}-games.csv`,filtered)}><ArrowDownToLine size={16}/>Export</Button></div><div className="ledger-filters"><Picker label="Split" value={split} onChange={setSplit} options={[{value:'all',label:'All opponents'},{value:'fbs',label:'FBS opponents'},{value:'home',label:'Home'},{value:'away',label:'Away'},{value:'neutral',label:'Neutral'}]}/><span>{filtered.length} games</span></div><Table><TableHeader><TableRow>{['Date','Opponent','Site','Result','Pregame win chance','Margin error'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{filtered.map(g=>{const home=g.home===team.id;const won=(g.hs>g.as)===home;const p=data.predictions.find(p=>p.id===g.id);return <TableRow key={g.id}><TableCell>{dateLabel(g.date)}</TableCell><TableCell><strong>{home?g.awayName:g.homeName}</strong>{!g.fbs&&<small className="muted">Non-FBS · not rated</small>}</TableCell><TableCell>{g.neutral?'Neutral':home?'Home':'Away'}</TableCell><TableCell><span className={won?'result-win':'result-loss'}>{won?'W':'L'}</span> {home?g.hs:g.as}–{home?g.as:g.hs}</TableCell><TableCell>{p?pct(home?p.prob:1-p.prob):'Not modeled'}</TableCell><TableCell>{p?`${Math.abs(p.margin-(g.hs-g.as)).toFixed(1)} pts`:'—'}</TableCell></TableRow>})}</TableBody></Table>{!filtered.length&&<p className="empty">No completed games in this split before the selected week.</p>}</section>}</>}
export function Stat({label,value,note}:{label:string;value:string;note:string}){return <div className="stat-item"><span>{label}</span><strong>{value}</strong><small>{note}</small></div>}
