"use client";
import {useState} from 'react';
import {ArrowDownToLine} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Table,TableHeader,TableBody,TableHead,TableRow,TableCell} from '@/components/ui/table';
import {Picker,Logo,signed,fixed,pct,dateLabel,download} from './ui';
import type {Team,Season,Snapshot} from './types';
export function Scouting({data,snapshot,week,selected,onSelect,onCompare}:{data:Season;snapshot:Snapshot;week:string;selected:string;onSelect:(v:string)=>void;onCompare:(v:string)=>void}){
const [split,setSplit]=useState('all');const team=snapshot.teams.find(t=>t.id===selected)??snapshot.teams[0];
const cutoff=data.weeks.indexOf(Number(week));const allowed=new Set(data.weeks.slice(0,cutoff));
const games=data.games.filter(g=>allowed.has(g.week)&&(g.home===team.id||g.away===team.id));
const filtered=games.filter(g=>split==='all'||split==='fbs'&&g.fbs||split==='home'&&!g.neutral&&g.home===team.id||split==='away'&&!g.neutral&&g.away===team.id||split==='neutral'&&g.neutral);
const trend=data.weeks.slice(0,cutoff+1).map(w=>({week:w,team:data.snapshots[String(w)].teams.find(t=>t.id===team.id)})).filter(x=>x.team);
const max=Math.max(20,...trend.map(t=>Math.abs(t.team!.power)))+3;const tx=(i:number)=>42+i/Math.max(1,trend.length-1)*670;const ty=(v:number)=>125-v/max*85;
const options=snapshot.teams.slice().sort((a,b)=>a.name.localeCompare(b.name)).map(t=>({value:t.id,label:t.name}));
return <><div className="section-heading"><div><h1>The scouting room<span>.</span></h1><p>Follow the team. Understand the shape of its season.</p></div><Picker label="Team" value={team.id} onChange={onSelect} options={options}/></div><section className="team-banner" style={{borderLeftColor:team.color}}><div className="team-identity"><Logo team={team} size={75}/><div><p>{team.conference}</p><h2>{team.name}</h2><span>{team.wins}–{team.losses} overall · {team.modelGames} FBS games in this season’s model</span></div></div><div className="team-national"><strong>#{team.rank}</strong><span>National power rank</span></div><Button onClick={()=>onCompare(team.id)}>Compare a matchup</Button></section>
<div className="stat-strip"><Stat label="Power rating" value={signed(team.power)} note="Points vs. average FBS"/><Stat label="Adjusted offense" value={signed(team.offense)} note="Points added / game"/><Stat label="Adjusted defense" value={signed(team.defense)} note="Points prevented / game"/><Stat label="Schedule strength" value={signed(team.sos)} note="Mean opponent net rating"/></div>
{team.modelGames<4&&<p className="callout">Small sample: {team.modelGames} FBS games. The prior-year rating and shrinkage still have a meaningful influence. A low early-season rating is not a final verdict.</p>}
<div className="two-col"><section className="surface"><div className="panel-title"><h2>The season, in strength</h2><span className="muted">Power / points</span></div><svg viewBox="0 0 760 260" className="trend-chart" role="img" aria-label={`${team.short} power rating trend through the selected week`}>{[-20,-10,0,10,20].map(n=><g key={n}><line x1="42" x2="712" y1={ty(n)} y2={ty(n)} stroke="#dce5eb" strokeDasharray={n===0?'0':'4 5'}/><text x="30" y={ty(n)+4} textAnchor="end">{n}</text></g>)}<polyline points={trend.map((p,i)=>`${tx(i)},${ty(p.team!.power)}`).join(' ')} fill="none" stroke="#1768ac" strokeWidth="3"/>{trend.map((p,i)=><g key={p.week}><circle cx={tx(i)} cy={ty(p.team!.power)} r="4" fill="#1768ac"><title>{p.week===99?'Latest':`Before ${p.week>=30?'postseason '+(p.week-30):'week '+p.week}`}: {signed(p.team!.power)}, rank #{p.team!.rank}</title></circle>{(i===0||i===trend.length-1||i%3===0)&&<text x={tx(i)} y="240" textAnchor="middle">{p.week===99?'Latest':p.week>=30?'Post':'W'+p.week}</text>}</g>)}</svg><p className="fine-print">Each point uses only games completed before that week. The first point is the offseason prior.</p></section><section className="surface"><h2>Inside the box score</h2><p className="subcopy">Season-to-date averages, all opponents. {team.boxGames} box scores available.</p><dl className="stat-list">{[['Points scored',fixed(team.pf)],['Points allowed',fixed(team.pa)],['Total yards',fixed(team.yards)],['Passing / rushing yards',`${fixed(team.passYards)} / ${fixed(team.rushYards)}`],['Opponent yards',fixed(team.yardsAllowed)],['Third-down conversion',pct(team.thirdDown)],['Pass completion',pct(team.completion)],['Turnovers / takeaways',`${fixed(team.turnovers)} / ${fixed(team.takeaways)}`]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></section></div>
<section className="surface ledger"><div className="panel-title"><div><h2>Every game leaves evidence</h2><p className="subcopy">Completed games through the selected snapshot. Predictions were frozen before each game’s week.</p></div><Button variant="outline" onClick={()=>download(`${team.abbr}-${data.season}-games.csv`,filtered)}><ArrowDownToLine size={16}/>Export</Button></div><div className="ledger-filters"><Picker label="Split" value={split} onChange={setSplit} options={[{value:'all',label:'All opponents'},{value:'fbs',label:'FBS opponents'},{value:'home',label:'Home'},{value:'away',label:'Away'},{value:'neutral',label:'Neutral'}]}/><span>{filtered.length} games</span></div><Table><TableHeader><TableRow>{['Date','Opponent','Site','Result','Pregame win chance','Margin error'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{filtered.map(g=>{const home=g.home===team.id;const won=(g.hs>g.as)===home;const p=data.predictions.find(p=>p.id===g.id);return <TableRow key={g.id}><TableCell>{dateLabel(g.date)}</TableCell><TableCell><strong>{home?g.awayName:g.homeName}</strong>{!g.fbs&&<small className="muted">Non-FBS · not rated</small>}</TableCell><TableCell>{g.neutral?'Neutral':home?'Home':'Away'}</TableCell><TableCell><span className={won?'result-win':'result-loss'}>{won?'W':'L'}</span> {home?g.hs:g.as}–{home?g.as:g.hs}</TableCell><TableCell>{p?pct(home?p.prob:1-p.prob):'Not modeled'}</TableCell><TableCell>{p?`${Math.abs(p.margin-(g.hs-g.as)).toFixed(1)} pts`:'—'}</TableCell></TableRow>})}</TableBody></Table>{!filtered.length&&<p className="empty">No completed games in this split before the selected week.</p>}</section></>}
export function Stat({label,value,note}:{label:string;value:string;note:string}){return <div className="stat-item"><span>{label}</span><strong>{value}</strong><small>{note}</small></div>}
