"use client";
import type {Team} from './types';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
export const signed=(n:number|null,d=1)=>n==null?'—':`${n>0?'+':''}${n.toFixed(d)}`;
export const fixed=(n:number|null|undefined,d=1)=>n==null?'—':n.toFixed(d);
export const pct=(n:number|null|undefined)=>n==null?'—':`${(n*100).toFixed(1)}%`;
export const weekName=(w:number)=>w===99?'Latest available':w>=30?`Before postseason ${w-30}`:`Before week ${w}`;
export const dateLabel=(v:string|null)=>v?new Date(v).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric',timeZone:'UTC'}):'Preseason';
export function Picker({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:{value:string;label:string}[]}){return <label className="picker"><span>{label}</span><Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select></label>}
export function Logo({team,size=32}:{team:Team;size?:number}){return <span className="team-logo" style={{width:size,height:size}}>{team.logo?<img src={team.logo} alt="" width={size} height={size} loading="lazy" onError={e=>{e.currentTarget.style.display='none'}}/>:team.abbr}</span>}
export function download(name:string,rows:object[]){if(!rows.length)return;const keys=Object.keys(rows[0]);const q=(v:unknown)=>`"${String(v??'').replaceAll('"','""')}"`;const blob=new Blob([keys.map(q).join(',')+'\n'+rows.map(r=>keys.map(k=>q((r as Record<string,unknown>)[k])).join(',')).join('\n')],{type:'text/csv;charset=utf-8;'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export function StrengthPlot({teams,onSelect}:{teams:Team[];onSelect:(id:string)=>void}){const x=(v:number)=>Math.max(35,Math.min(425,230+v/32*190)),y=(v:number)=>Math.max(26,Math.min(325,175-v/32*145));return <svg viewBox="0 0 460 375" className="strength-chart" role="img" aria-label="Adjusted offense horizontally and defense vertically. Right and up are better."><rect x="30" y="22" width="400" height="308" rx="5" fill="#edf4f6"/>{[-30,-15,0,15,30].map(n=><g key={n}><line x1={x(n)} x2={x(n)} y1="22" y2="330" stroke={n===0?'#9dafb9':'#d7e2e7'} strokeDasharray={n===0?'0':'3 5'}/><line x1="30" x2="430" y1={y(n)} y2={y(n)} stroke={n===0?'#9dafb9':'#d7e2e7'} strokeDasharray={n===0?'0':'3 5'}/><text x={x(n)} y="350" textAnchor="middle">{n}</text><text x="22" y={y(n)+4} textAnchor="end">{n}</text></g>)}<text x="416" y="44" textAnchor="end" className="quadrant">Complete teams</text><text x="44" y="313" className="quadrant">Room to improve</text>{teams.slice().reverse().map(t=><g key={t.id} role="button" tabIndex={0} aria-label={`${t.short}: offense ${t.offense.toFixed(1)}, defense ${t.defense.toFixed(1)}`} onClick={()=>onSelect(t.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelect(t.id)}}} className="plot-point"><title>{t.name}: offense {signed(t.offense)}, defense {signed(t.defense)}</title><circle cx={x(t.offense)} cy={y(t.defense)} r={t.rank<=10?6:3.3} fill={t.rank<=10?t.color:'#7b9caa'} opacity={t.rank<=10?1:.5} stroke="white" strokeWidth="1"/>{t.rank<=5&&<text x={x(t.offense)+9} y={y(t.defense)+4} className="point-label">{t.abbr}</text>}</g>)}<text x="230" y="373" textAnchor="middle" className="axis-label">Better offense (points / game)</text></svg>}
