"use client";
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {CalendarDays,CloudSun,MapPin,Radio} from 'lucide-react';
import type {CatalogGame} from '@/lib/server-catalog';
import type {Season,Team} from '@/app/types';
import {asset} from '@/lib/paths';
import {modelPredict} from '@/lib/model';
import {predict} from '@/lib/predict';
import {teamPath} from '@/lib/routes';
import {Logo,dateLabel,fixed,pct,signed} from '@/app/ui';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';

type FixtureFeed={games:CatalogGame[];fetchedAt:string};
const kickoff=(date:string,timeValid:boolean)=>timeValid?new Date(date).toLocaleString('en-US',{weekday:'long',month:'long',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit',timeZone:'America/New_York',timeZoneName:'short'}):`${dateLabel(date)} · kickoff time TBD`;
const TeamIdentity=({team,name,side}:{team?:Team;name:string;side:'away'|'home'})=><div className={`game-team ${side}`}>{team?<Link href={teamPath(team)}><Logo team={team} size={82}/><span>#{team.modelRank??team.rank} · {team.wins}–{team.losses}</span><h2>{team.short}</h2><small>Open team report →</small></Link>:<><span className="team-placeholder">{name.slice(0,2).toUpperCase()}</span><h2>{name}</h2><small>Outside this season’s FBS field</small></>}</div>;

export function GamePageClient({game}:{game:CatalogGame}){
  const [data,setData]=useState<Season|null>(null),[fixtures,setFixtures]=useState<FixtureFeed|null>(null),[error,setError]=useState('');
  useEffect(()=>{const c=new AbortController();const jobs=[fetch(asset(`/data/${game.season}.json`),{signal:c.signal}).then(r=>r.json()).then(d=>setData(d as Season))];if(game.season===2026)jobs.push(fetch(asset('/data/fixtures.json'),{signal:c.signal}).then(r=>r.json()).then(d=>setFixtures(d as FixtureFeed)));Promise.all(jobs).catch(e=>{if(e.name!=='AbortError')setError('Game data could not load.')});return()=>c.abort()},[game.season]);
  const view=useMemo(()=>{
    if(!data)return null;const snapshot=data.snapshots['99'],away=snapshot.teams.find(t=>t.id===game.away),home=snapshot.teams.find(t=>t.id===game.home),played=data.games.find(g=>g.id===game.id),prediction=data.predictions.find(p=>p.id===game.id);
    let awayProbability: number|null=prediction?1-prediction.prob:null;const score:null|ReturnType<typeof predict>=away&&home?predict(away,home,snapshot.mu,game.neutral?'neutral':'b',data.scoringConfig!):null;
    if(!game.completed&&away?.modelState&&home?.modelState&&data.model){const schedule=fixtures?.games??[];const scheduledState=(team:Team)=>{const prior=schedule.filter(f=>f.date<game.date&&(f.completed||f.status==='STATUS_SCHEDULED')&&(f.home===team.id||f.away===team.id)).map(f=>f.date).sort().at(-1);return {...team.modelState!,lastDate:prior??team.modelState!.lastDate}};awayProbability=modelPredict(scheduledState(away),scheduledState(home),game.neutral?0:-1,data.model,game.date).probability}
    return {snapshot,away,home,played,prediction,awayProbability,score};
  },[data,fixtures,game]);
  if(error)return <main><div className="notice">{error}</div></main>;if(!view)return <main><div className="loading">Loading game center…</div></main>;
  const {away,home,played,prediction,awayProbability,score}=view,awayScore=played?.as??game.as,homeScore=played?.hs??game.hs,completed=Boolean(played||game.completed),winner=completed&&awayScore!==null&&homeScore!==null?(awayScore>homeScore?'away':'home'):null;
  const meetings=data!.games.filter(g=>g.id!==game.id&&((g.away===game.away&&g.home===game.home)||(g.away===game.home&&g.home===game.away))).slice(-5).reverse();
  const metrics=away&&home?[['Strength index',pct(away.winIndex),pct(home.winIndex)],['Scoring power',signed(away.power),signed(home.power)],['Adjusted offense',signed(away.offense),signed(home.offense)],['Adjusted defense',signed(away.defense),signed(home.defense)],['Schedule strength',signed(away.sos),signed(home.sos)],['Net EPA / play',fixed(away.modelState?.q?.[1],3),fixed(home.modelState?.q?.[1],3)],['Yards / play',fixed(away.modelState?.q?.[11],3),fixed(home.modelState?.q?.[11],3)],['Points / game',fixed(away.pf),fixed(home.pf)]]:[];
  return <main className="game-page"><div className="game-kicker"><span>{game.season} · Week {game.week}</span><strong>{completed?'FINAL':'UPCOMING'}</strong></div><section className="game-hero"><TeamIdentity team={away} name={game.awayName} side="away"/><div className="game-center">{completed?<><span>Final</span><div><strong className={winner==='away'?'winner':''}>{awayScore}</strong><i>–</i><strong className={winner==='home'?'winner':''}>{homeScore}</strong></div></>:<><span>Saturday Lab forecast</span><div><strong>{awayProbability==null?'—':Math.round(awayProbability*100)}</strong><i>%</i><strong>{awayProbability==null?'—':Math.round((1-awayProbability)*100)}</strong></div><p>{awayProbability==null?'Not modeled':Math.abs(awayProbability-.5)<.1?'Close matchup':awayProbability>.5?`${away?.short??game.awayName} favored`:`${home?.short??game.homeName} favored`}</p></>}<small>{game.neutral?'Neutral site':`${home?.short??game.homeName} home game`}</small></div><TeamIdentity team={home} name={game.homeName} side="home"/><div className="probability-track">{awayProbability!=null&&<><span style={{width:`${awayProbability*100}%`,background:away?.color??'#657786'}}/><span style={{flex:1,background:home?.color??'#aeb8bf'}}/></>}</div></section>
  <section className="game-facts"><div><CalendarDays/><span><small>Kickoff</small><strong>{kickoff(game.date,game.timeValid)}</strong></span></div><div><MapPin/><span><small>Site</small><strong>{game.neutral?'Neutral site; venue name unavailable in this snapshot':`${home?.name??game.homeName} home field`}</strong></span></div><div><CloudSun/><span><small>Weather</small><strong>{completed?'Not stored in the published game dataset':'Forecast not yet stored'}</strong></span></div><div><Radio/><span><small>Coverage</small><strong>{game.fbs?'FBS matchup':'Includes a non-FBS opponent'}</strong></span></div></section>
  {!completed&&score&&<section className="surface game-projection"><div><span>Scoring-component estimate</span><strong>{away?.abbr} {Math.max(0,score.aScore).toFixed(1)} – {home?.abbr} {Math.max(0,score.bScore).toFixed(1)}</strong></div><div><span>Expected margin</span><strong>{score.margin>=0?away?.short:home?.short} by {Math.abs(score.margin).toFixed(1)}</strong></div><p>Win probability uses the complete v6 model and the scheduled venue/date. The score estimate uses its opponent-adjusted scoring component.</p></section>}
  {completed&&prediction&&<section className="surface game-projection"><div><span>Pregame home win probability</span><strong>{pct(prediction.prob)}</strong></div><div><span>Pregame expected margin</span><strong>{home?.short??game.homeName} {signed(prediction.margin)}</strong></div><div><span>Prediction error</span><strong>{Math.abs(prediction.margin-Number(homeScore! - awayScore!)).toFixed(1)} pts</strong></div><p>This frozen reconstruction uses only information available before the game.</p></section>}
  {away&&home&&<section className="surface compare-surface"><div className="panel-title"><div><h2>Team profile at this snapshot</h2><p className="subcopy">Opponent-adjusted ratings and season production.</p></div></div><Table><TableHeader><TableRow><TableHead>Metric</TableHead><TableHead>{away.short}</TableHead><TableHead>{home.short}</TableHead></TableRow></TableHeader><TableBody>{metrics.map(row=><TableRow key={row[0]}><TableCell>{row[0]}</TableCell><TableCell>{row[1]}</TableCell><TableCell>{row[2]}</TableCell></TableRow>)}</TableBody></Table></section>}
  <section className="surface"><h2>Recent meetings in the archive</h2>{meetings.length?meetings.map(g=><p className="meeting" key={g.id}>{dateLabel(g.date)} · {g.awayName} {g.as} – {g.hs} {g.homeName}{g.neutral?' · neutral':''}</p>):<p className="subcopy">No other meeting appears in this season’s published archive.</p>}</section><p className="game-source-note">Schedule and result records are ESPN-derived through SportsDataverse or the public ESPN schedule feed. Saturday Lab is independent and is not affiliated with ESPN, the NCAA or either university.</p></main>;
}
