"use client";
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {ArrowLeft,CalendarDays,ChevronRight,MapPin,Radio} from 'lucide-react';
import type {CatalogGame} from '@/lib/server-catalog';
import type {Season,Team} from '@/app/types';
import {asset} from '@/lib/paths';
import {modelPredict} from '@/lib/model';
import {predict} from '@/lib/predict';
import {gamePath,teamPath} from '@/lib/routes';
import {gamePathFrom,readGameReturn,rememberGameOrigin} from '@/lib/game-navigation';
import {fullModelScore} from '@/lib/projected-score';
import {fetchLiveFeed,type LiveFeed,type LiveGame} from '@/lib/live-feed';
import {Logo,dateLabel,fixed,pct,signed} from '@/app/ui';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';

type FixtureFeed={games:CatalogGame[];fetchedAt:string};
type BoxValues=Record<string,number|null>;
type BoxRow={gameId:string;teamId:string;opponentId:string;own:BoxValues;opponent:BoxValues|null};
type BoxData={rows:BoxRow[];source:string};
type PeriodData={games:Record<string,{away:number[];home:number[]}>};
const kickoff=(date:string,timeValid:boolean)=>timeValid?new Date(date).toLocaleString('en-US',{weekday:'long',month:'long',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit',timeZone:'America/New_York',timeZoneName:'short'}):`${dateLabel(date)} · kickoff time TBD`;
const boxNumber=(value:number|null|undefined,digits=0)=>value==null?'—':value.toFixed(digits);
const boxPair=(made:number|null|undefined,attempts:number|null|undefined)=>made==null||attempts==null?'—':`${made.toFixed(0)} / ${attempts.toFixed(0)}`;
const boxPercent=(value:number|null|undefined)=>value==null?'—':`${(value*100).toFixed(1)}%`;
const TeamIdentity=({team,name,side}:{team?:Team;name:string;side:'away'|'home'})=><div className={`game-team ${side}`}>{team?<Link href={teamPath(team)}><Logo team={team} size={82}/><span>#{team.modelRank??team.rank} · {team.wins}–{team.losses}</span><h2>{team.short}</h2><small>Open team report →</small></Link>:<><span className="team-placeholder">{name.slice(0,2).toUpperCase()}</span><h2>{name}</h2><small>Outside this season’s FBS field</small></>}</div>;

function GameBack(){
  const router=useRouter(),[target,setTarget]=useState(()=>({path:'/games/',label:'Scores & schedule',canHistoryBack:false}));
  useEffect(()=>{let active=true;queueMicrotask(()=>{if(active)setTarget(readGameReturn())});return()=>{active=false}},[]);
  return <button className="game-back" onClick={()=>target.canHistoryBack?window.history.back():router.push(target.path)}><ArrowLeft size={16}/> Back to {target.label}</button>;
}

export function GamePageClient({game,meetings}:{game:CatalogGame;meetings:CatalogGame[]}){
  const [data,setData]=useState<Season|null>(null),[fixtures,setFixtures]=useState<FixtureFeed|null>(null),[live,setLive]=useState<LiveFeed|null>(null),[box,setBox]=useState<BoxData|null>(null),[periods,setPeriods]=useState<PeriodData|null>(null),[currentReturnPath,setCurrentReturnPath]=useState(gamePath(game)),[error,setError]=useState('');
  useEffect(()=>{const c=new AbortController();const jobs=[fetch(asset(`/data/${game.season}.json`),{signal:c.signal}).then(r=>r.json()).then(d=>setData(d as Season))];if(game.season===2026){jobs.push(fetch(asset('/data/fixtures.json'),{signal:c.signal}).then(r=>r.json()).then(d=>setFixtures(d as FixtureFeed)));jobs.push(fetchLiveFeed(2026,c.signal).then(setLive).catch(()=>undefined))}if(game.completed){jobs.push(fetch(asset(`/data/box-${game.season}.json`),{signal:c.signal}).then(r=>r.json()).then(d=>setBox(d as BoxData)));jobs.push(fetch(asset(`/data/periods-${game.season}.json`),{signal:c.signal}).then(r=>r.json()).then(d=>setPeriods(d as PeriodData)))}Promise.all(jobs).catch(e=>{if(e.name!=='AbortError')setError('Game data could not load. Refresh the page to try again.')});return()=>c.abort()},[game.season,game.completed]);
  useEffect(()=>{let active=true;queueMicrotask(()=>{if(!active)return;const base=process.env.NEXT_PUBLIC_BASE_PATH??'',path=window.location.pathname.startsWith(base)?window.location.pathname.slice(base.length):window.location.pathname;setCurrentReturnPath(`${path}${window.location.search}`)});return()=>{active=false}},[game.id]);
  const view=useMemo(()=>{
    if(!data)return null;const current=(live?.games.find(row=>row.id===game.id)??game) as CatalogGame|LiveGame,snapshot=data.snapshots['99'],away=snapshot.teams.find(t=>t.id===game.away),home=snapshot.teams.find(t=>t.id===game.home),played=data.games.find(g=>g.id===game.id),prediction=data.predictions.find(p=>p.id===game.id);
    let awayProbability: number|null=prediction?1-prediction.prob:current&&'pregame' in current&&current.pregame?1-current.pregame.homeWinProbability:null;const score:null|ReturnType<typeof predict>=away&&home?predict(away,home,snapshot.mu,game.neutral?'neutral':'b',data.scoringConfig!):null;
    if(!current.completed&&(!('state' in current)||current.state!=='in')&&away?.modelState&&home?.modelState&&data.model){const schedule=(live?.games??fixtures?.games??[]);const scheduledState=(team:Team)=>{const prior=schedule.filter(f=>f.date<current.date&&(f.completed||f.status==='STATUS_SCHEDULED')&&(f.home===team.id||f.away===team.id)).map(f=>f.date).sort().at(-1);return {...team.modelState!,lastDate:prior??team.modelState!.lastDate}};awayProbability=modelPredict(scheduledState(away),scheduledState(home),game.neutral?0:-1,data.model,current.date).probability}
    return {snapshot,away,home,played,prediction,awayProbability,score,current};
  },[data,fixtures,live,game]);
  if(error)return <main className="game-page"><div className="notice">{error}</div></main>;if(!view)return <main className="game-page game-page-loading"><div className="loading">Loading game center…</div></main>;
  const {away,home,played,prediction,awayProbability,score,current}=view,liveGame='state' in current?current:null,projectedScore=score&&awayProbability!=null?fullModelScore(awayProbability,score.aScore,score.bScore):null,awayScore=liveGame?.as??played?.as??game.as,homeScore=liveGame?.hs??played?.hs??game.hs,completed=Boolean(liveGame?.completed||played||game.completed),inProgress=liveGame?.state==='in',scoreAvailable=(completed||inProgress)&&awayScore!==null&&homeScore!==null,winner=completed&&awayScore!==null&&homeScore!==null?(awayScore>homeScore?'away':'home'):null;
  const metrics=away&&home?[['Record',`${away.wins}–${away.losses}`,`${home.wins}–${home.losses}`],['National power rank',`#${away.modelRank??away.rank}`,`#${home.modelRank??home.rank}`],['Strength index',pct(away.winIndex),pct(home.winIndex)],['Scoring power',signed(away.power),signed(home.power)],['Adjusted offense',signed(away.offense),signed(home.offense)],['Adjusted defense',signed(away.defense),signed(home.defense)],['Schedule strength',signed(away.sos),signed(home.sos)],['Net EPA / play',fixed(away.modelState?.q?.[1],3),fixed(home.modelState?.q?.[1],3)],['Adjusted yards / play',fixed(away.modelState?.q?.[11],3),fixed(home.modelState?.q?.[11],3)],['Points / game',fixed(away.pf),fixed(home.pf)],['Points allowed / game',fixed(away.pa),fixed(home.pa)],['Total yards / game',fixed(away.yards),fixed(home.yards)],['Passing yards / game',fixed(away.passYards),fixed(home.passYards)],['Rushing yards / game',fixed(away.rushYards),fixed(home.rushYards)],['Yards allowed / game',fixed(away.yardsAllowed),fixed(home.yardsAllowed)],['Third-down conversion',pct(away.thirdDown),pct(home.thirdDown)],['Completion rate',pct(away.completion),pct(home.completion)],['Turnovers / game',fixed(away.turnovers),fixed(home.turnovers)],['Takeaways / game',fixed(away.takeaways),fixed(home.takeaways)]]:[];
  const rawBox=box?.rows.find(r=>r.gameId===game.id&&(r.teamId===game.away||r.teamId===game.home)),liveBox=liveGame?.detail?.box,awayBox=liveBox?.[game.away]??(rawBox?.teamId===game.away?rawBox.own:rawBox?.opponent),homeBox=liveBox?.[game.home]??(rawBox?.teamId===game.home?rawBox.own:rawBox?.opponent);
  const periodScore=liveGame?.detail?.periods??periods?.games[game.id],periodCount=periodScore?Math.max(periodScore.away.length,periodScore.home.length):0,periodLabels=Array.from({length:periodCount},(_,index)=>index<4?`Q${index+1}`:index===4?'OT':`${index-3}OT`);
  const boxMetrics=awayBox&&homeBox?[['First downs',boxNumber(awayBox.firstDowns),boxNumber(homeBox.firstDowns)],['Total yards',boxNumber(awayBox.totalYards),boxNumber(homeBox.totalYards)],['Passing yards',boxNumber(awayBox.passYards),boxNumber(homeBox.passYards)],['Rushing yards',boxNumber(awayBox.rushYards),boxNumber(homeBox.rushYards)],['Pass completions / attempts',boxPair(awayBox.passCompletions,awayBox.passAttempts),boxPair(homeBox.passCompletions,homeBox.passAttempts)],['Rushing attempts',boxNumber(awayBox.rushAttempts),boxNumber(homeBox.rushAttempts)],['Play-volume proxy',boxNumber(awayBox.plays),boxNumber(homeBox.plays)],['Yards / play proxy',boxNumber(awayBox.yardsPerPlay,2),boxNumber(homeBox.yardsPerPlay,2)],['Third downs',boxPair(awayBox.thirdMade,awayBox.thirdAttempts),boxPair(homeBox.thirdMade,homeBox.thirdAttempts)],['Third-down rate',boxPercent(awayBox.thirdRate),boxPercent(homeBox.thirdRate)],['Fourth downs',boxPair(awayBox.fourthMade,awayBox.fourthAttempts),boxPair(homeBox.fourthMade,homeBox.fourthAttempts)],['Turnovers',boxNumber(awayBox.turnovers),boxNumber(homeBox.turnovers)],['Penalties / yards',boxPair(awayBox.penalties,awayBox.penaltyYards),boxPair(homeBox.penalties,homeBox.penaltyYards)],['Possession',`${boxNumber(awayBox.possessionMinutes,1)} min`,`${boxNumber(homeBox.possessionMinutes,1)} min`]]:[];
  const pregameHome=prediction?.prob??liveGame?.pregame?.homeWinProbability??null,venue=liveGame?.detail?.venue,venueLabel=venue?.name?[venue.name,[venue.city,venue.state].filter(Boolean).join(', ')].filter(Boolean).join(' · '):game.neutral?'Neutral site':`${home?.name??game.homeName} home game`,coverageLabel=liveGame?.detail?.broadcast??liveGame?.broadcast??(game.fbs?'FBS matchup':'Includes a non-FBS opponent');
  return <main className="game-page"><div className="game-kicker"><GameBack/><span>{game.season} · Week {game.week}</span><strong>{completed?'FINAL':inProgress?'LIVE':'UPCOMING'}</strong></div><section className="game-hero"><TeamIdentity team={away} name={game.awayName} side="away"/><div className="game-center">{scoreAvailable?<><span>{completed?'Final':liveGame?.statusDetail??'Live'}</span><div><strong className={winner==='away'?'winner':''}>{awayScore}</strong><i>–</i><strong className={winner==='home'?'winner':''}>{homeScore}</strong></div></>:<><span>Saturday Lab forecast</span><div><strong>{awayProbability==null?'—':(awayProbability*100).toFixed(1)}</strong><i>%</i><strong>{awayProbability==null?'—':((1-awayProbability)*100).toFixed(1)}</strong></div><p>{awayProbability==null?'Not modeled':Math.abs(awayProbability-.5)<.1?'Close matchup':awayProbability>.5?`${away?.short??game.awayName} favored`:`${home?.short??game.homeName} favored`}</p></>}<small>{game.neutral?'Neutral site':`${home?.short??game.homeName} home game`}</small></div><TeamIdentity team={home} name={game.homeName} side="home"/><div className="probability-track">{awayProbability!=null&&<><span style={{width:`${awayProbability*100}%`,background:away?.color??'#657786'}}/><span style={{flex:1,background:home?.color??'#aeb8bf'}}/></>}</div></section>
  <section className="game-facts"><div><CalendarDays/><span><small>Kickoff</small><strong>{kickoff(current.date,current.timeValid)}</strong></span></div><div><MapPin/><span><small>Site</small><strong>{venueLabel}</strong></span></div><div><Radio/><span><small>Coverage</small><strong>{coverageLabel}</strong></span></div></section>
  {scoreAvailable&&<section className="surface period-score"><div className="panel-title"><h2>Score by quarter</h2><span>{completed?'Final':liveGame?.statusDetail??'Live'}</span></div>{periodScore?<div className="period-score-scroll"><table><thead><tr><th>Team</th>{periodLabels.map(label=><th key={label}>{label}</th>)}<th>{completed?'Final':'Total'}</th></tr></thead><tbody><tr><th>{away?.abbr??game.awayName}</th>{periodLabels.map((_,index)=><td key={index}>{periodScore.away[index]??'—'}</td>)}<td>{awayScore}</td></tr><tr><th>{home?.abbr??game.homeName}</th>{periodLabels.map((_,index)=><td key={index}>{periodScore.home[index]??'—'}</td>)}<td>{homeScore}</td></tr></tbody></table></div>:<p className="subcopy period-unavailable">Quarter-by-quarter scoring is unavailable for this record.</p>}</section>}
  {!completed&&!inProgress&&projectedScore&&<section className="surface game-projection"><div><span>Full-model expected score</span><strong>{away?.abbr} {projectedScore.aScore.toFixed(1)} – {home?.abbr} {projectedScore.bScore.toFixed(1)}</strong></div><div><span>Expected margin</span><strong>{projectedScore.margin>=0?away?.short:home?.short} by {Math.abs(projectedScore.margin).toFixed(1)}</strong></div><p>The v6 win signal sets the margin; a historical calibration of the opponent-adjusted scoring total sets the pace. These are expected points, not an exact-score prediction.</p></section>}
  {scoreAvailable&&pregameHome!=null&&<section className="surface game-projection"><div><span>Pregame home win probability</span><strong>{pct(pregameHome)}</strong></div>{prediction&&<><div><span>Pregame expected margin</span><strong>{home?.short??game.homeName} {signed(prediction.margin)}</strong></div><div><span>Prediction error</span><strong>{Math.abs(prediction.margin-Number(homeScore! - awayScore!)).toFixed(1)} pts</strong></div></>}<p>This prediction is frozen from the weekly model snapshot available before kickoff.</p></section>}
  {scoreAvailable&&<section className="surface game-box-score"><div className="panel-title"><h2>Full team box score</h2></div>{boxMetrics.length?<Table><TableHeader><TableRow><TableHead>Statistic</TableHead><TableHead>{away?.short??game.awayName}</TableHead><TableHead>{home?.short??game.homeName}</TableHead></TableRow></TableHeader><TableBody>{boxMetrics.map(row=><TableRow key={row[0]}><TableCell>{row[0]}</TableCell><TableCell>{row[1]}</TableCell><TableCell>{row[2]}</TableCell></TableRow>)}</TableBody></Table>:<p className="subcopy">A complete team box score is not available for this game in the published archive.</p>}<p className="fine-print">Play volume is pass attempts + rushing attempts and follows the source’s sack conventions. Possession is converted to minutes. Missing values remain blank rather than being treated as zero.</p></section>}
  {away&&home&&<section className="surface compare-surface"><div className="panel-title"><div><h2>Team profile at this snapshot</h2><p className="subcopy">Opponent-adjusted ratings and season production.</p></div></div><Table><TableHeader><TableRow><TableHead>Metric</TableHead><TableHead>{away.short}</TableHead><TableHead>{home.short}</TableHead></TableRow></TableHeader><TableBody>{metrics.map(row=><TableRow key={row[0]}><TableCell>{row[0]}</TableCell><TableCell>{row[1]}</TableCell><TableCell>{row[2]}</TableCell></TableRow>)}</TableBody></Table></section>}
  <section className="surface meeting-history"><div className="panel-title"><div><h2>Previous meetings</h2><p className="subcopy">The latest meetings in this game’s season and the four seasons before it.</p></div></div>{meetings.length?meetings.map(g=>{const source={path:currentReturnPath,label:`${away?.short??game.awayName} ${game.neutral?'vs.':'at'} ${home?.short??game.homeName}`},href=gamePathFrom(g,source);return <Link className="meeting-link" href={href} onClick={()=>rememberGameOrigin(href,source)} key={g.id}><span><small>{g.season} season · {dateLabel(g.date)}{g.neutral?' · neutral site':''}</small><strong>{g.awayName} {g.as} – {g.hs} {g.homeName}</strong></span><ChevronRight size={18}/></Link>}):<p className="subcopy meeting-empty">No earlier meeting appears in the five-season archive window.</p>}</section><p className="game-source-note">Scores, schedules, team box scores and period scoring are ESPN-derived through SportsDataverse or the public ESPN schedule feed. Saturday Lab is independent and is not affiliated with ESPN, the NCAA or either university.</p></main>;
}
